;;; kanso-pearl-theme.el --- Kanso Pearl — a calm Kansō theme ported from Zed -*- lexical-binding: t; -*-

;; Author: Ported from webhooked/kanso-zed (Kansō by Webhooked)
;; Maintainer: Kansō Emacs port
;; Version: 1.0.0
;; Keywords: faces, theme, light
;; Homepage: https://github.com/webhooked/kanso-zed
;; Package-Requires: ((emacs "27.1"))

;;; Commentary:
;; Kanso Pearl: a light theme from the Kansō family — an elegant evolution
;; of the Kanagawa palette that invites focus, not attention.
;;
;; Ported from the upstream Zed theme.  Supports font-lock, tree-sitter
;; (both built-in treesit and the tree-sitter-hl-face:* package), doom-modeline,
;; magit, lsp-mode / eglot, flycheck / flymake, org, markdown, dired,
;; company / corfu / vertico / ivy / helm, which-key, tab-bar / tab-line,
;; terminal (term / vterm / ansi-color) and many more.

;;; Code:

(deftheme kanso-pearl
  "Kanso Pearl — a light theme from the Kansō family (ported from Zed).")

(let ((class '((class color) (min-colors 89)))
  )

  (custom-theme-set-faces
   'kanso-pearl
   `(default ((,class (:foreground "#22262D" :background "#f2f1ef"))))
   `(cursor ((,class (:background "#22262D"))))
   `(fringe ((,class (:background "#f2f1ef" :foreground "#6D6D69"))))
   `(region ((,class (:background "#C6C6C5" :extend t))))
   `(highlight ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(hl-line ((,class (:background "#e2e1df" :extend t))))
   `(secondary-selection ((,class (:background "#9fb5c9" :extend t))))
   `(lazy-highlight ((,class (:background "#9fb5c9" :foreground "#22262D"))))
   `(isearch ((,class (:background "#77713F" :foreground "#f2f1ef"))))
   `(isearch-fail ((,class (:background "#D7474B" :foreground "#f2f1ef"))))
   `(match ((,class (:background "#9fb5c9" :foreground "#22262D"))))
   `(minibuffer-prompt ((,class (:foreground "#4D699B"))))
   `(escape-glyph ((,class (:foreground "#4d699b"))))
   `(homoglyph ((,class (:foreground "#4d699b"))))
   `(trailing-whitespace ((,class (:background "#D7474B"))))
   `(nobreak-space ((,class (:foreground "#6D6D69"))))
   `(nobreak-hyphen ((,class (:foreground "#6D6D69"))))
   `(shadow ((,class (:foreground "#6D6D69"))))
   `(link ((,class (:foreground "#4D699B" :underline t))))
   `(link-visited ((,class (:foreground "#624C83" :underline t))))
   `(success ((,class (:foreground "#6E915F"))))
   `(warning ((,class (:foreground "#77713f"))))
   `(error ((,class (:foreground "#D7474B"))))
   `(tooltip ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(vertical-border ((,class (:foreground "#dddddb"))))
   `(window-divider ((,class (:foreground "#dddddb"))))
   `(window-divider-first-pixel ((,class (:foreground "#dddddb"))))
   `(window-divider-last-pixel ((,class (:foreground "#dddddb"))))
   `(fill-column-indicator ((,class (:foreground "#f2f1ef"))))
   `(separator-line ((,class (:foreground "#dddddb"))))
   `(help-key-binding ((,class (:foreground "#4D699B" :background "#f2f1ef" :box (:line-width 1 :color "#dddddb")))))
   `(header-line ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(widget-field ((,class (:background "#f2f1ef" :foreground "#22262D" :extend t))))
   `(widget-single-line-field ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(button ((,class (:foreground "#4D699B" :underline t))))
   `(custom-button ((,class (:background "#f2f1ef" :foreground "#22262D" :box (:line-width 1 :color "#dddddb")))))
   `(custom-variable-tag ((,class (:foreground "#4D699B"))))
   `(custom-group-tag ((,class (:foreground "#624C83"))))
   `(custom-state ((,class (:foreground "#6F894E"))))
   `(line-number ((,class (:foreground "#9F9F99" :background "#f2f1ef"))))
   `(line-number-current-line ((,class (:foreground "#22262D" :background "#e2e1df"))))
   `(linum ((,class (:foreground "#9F9F99" :background "#f2f1ef"))))
   `(mode-line ((,class (:background "#f2f1ef" :foreground "#22262D" :box (:line-width -1 :color "#dddddb")))))
   `(mode-line-inactive ((,class (:background "#f2f1ef" :foreground "#6D6D69" :box (:line-width -1 :color "#dddddb")))))
   `(mode-line-emphasis ((,class (:foreground "#4D699B"))))
   `(mode-line-highlight ((,class (:foreground "#5E857A"))))
   `(mode-line-buffer-id ((,class (:foreground "#22262D"))))
   `(font-lock-comment-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-doc-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#597B75"))))
   `(font-lock-string-face ((,class (:foreground "#6F894E"))))
   `(font-lock-keyword-face ((,class (:foreground "#624C83"))))
   `(font-lock-builtin-face ((,class (:foreground "#624C83"))))
   `(font-lock-function-name-face ((,class (:foreground "#4D699B"))))
   `(font-lock-function-call-face ((,class (:foreground "#4D699B"))))
   `(font-lock-variable-name-face ((,class (:foreground "#22262D"))))
   `(font-lock-variable-use-face ((,class (:foreground "#22262D"))))
   `(font-lock-type-face ((,class (:foreground "#597B75"))))
   `(font-lock-constant-face ((,class (:foreground "#CC6D00"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-negation-char-face ((,class (:foreground "#D7474B"))))
   `(font-lock-warning-face ((,class (:foreground "#77713f"))))
   `(font-lock-number-face ((,class (:foreground "#B35B79"))))
   `(font-lock-operator-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-property-name-face ((,class (:foreground "#77713F"))))
   `(font-lock-property-use-face ((,class (:foreground "#77713F"))))
   `(font-lock-punctuation-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-bracket-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-delimiter-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-escape-face ((,class (:foreground "#6F894E"))))
   `(font-lock-misc-punctuation-face ((,class (:foreground "#6D6D69"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#6F894E"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#6F894E"))))
   `(tree-sitter-hl-face:attribute ((,class (:foreground "#624C83"))))
   `(tree-sitter-hl-face:comment ((,class (:foreground "#6D6D69"))))
   `(tree-sitter-hl-face:constant ((,class (:foreground "#CC6D00"))))
   `(tree-sitter-hl-face:constant.builtin ((,class (:foreground "#CC6D00"))))
   `(tree-sitter-hl-face:constructor ((,class (:foreground "#4D699B"))))
   `(tree-sitter-hl-face:escape ((,class (:foreground "#6F894E"))))
   `(tree-sitter-hl-face:embedded ((,class (:foreground "#CC6D00"))))
   `(tree-sitter-hl-face:function ((,class (:foreground "#4D699B"))))
   `(tree-sitter-hl-face:function.builtin ((,class (:foreground "#4D699B"))))
   `(tree-sitter-hl-face:function.call ((,class (:foreground "#4D699B"))))
   `(tree-sitter-hl-face:function.macro ((,class (:foreground "#624C83"))))
   `(tree-sitter-hl-face:function.method ((,class (:foreground "#4D699B"))))
   `(tree-sitter-hl-face:function.method.call ((,class (:foreground "#4D699B"))))
   `(tree-sitter-hl-face:keyword ((,class (:foreground "#624C83"))))
   `(tree-sitter-hl-face:label ((,class (:foreground "#B35B79"))))
   `(tree-sitter-hl-face:method ((,class (:foreground "#4D699B"))))
   `(tree-sitter-hl-face:method.call ((,class (:foreground "#4D699B"))))
   `(tree-sitter-hl-face:number ((,class (:foreground "#B35B79"))))
   `(tree-sitter-hl-face:operator ((,class (:foreground "#6D6D69"))))
   `(tree-sitter-hl-face:property ((,class (:foreground "#77713F"))))
   `(tree-sitter-hl-face:property.definition ((,class (:foreground "#77713F"))))
   `(tree-sitter-hl-face:punctuation ((,class (:foreground "#6D6D69"))))
   `(tree-sitter-hl-face:punctuation.bracket ((,class (:foreground "#6D6D69"))))
   `(tree-sitter-hl-face:punctuation.delimiter ((,class (:foreground "#6D6D69"))))
   `(tree-sitter-hl-face:punctuation.special ((,class (:foreground "#D7474B"))))
   `(tree-sitter-hl-face:string ((,class (:foreground "#6F894E"))))
   `(tree-sitter-hl-face:string.special ((,class (:foreground "#6F894E"))))
   `(tree-sitter-hl-face:tag ((,class (:foreground "#77713F"))))
   `(tree-sitter-hl-face:type ((,class (:foreground "#597B75"))))
   `(tree-sitter-hl-face:type.argument ((,class (:foreground "#597B75"))))
   `(tree-sitter-hl-face:type.builtin ((,class (:foreground "#597B75"))))
   `(tree-sitter-hl-face:type.parameter ((,class (:foreground "#597B75"))))
   `(tree-sitter-hl-face:type.super ((,class (:foreground "#597B75"))))
   `(tree-sitter-hl-face:variable ((,class (:foreground "#22262D"))))
   `(tree-sitter-hl-face:variable.builtin ((,class (:foreground "#D7474B"))))
   `(tree-sitter-hl-face:variable.parameter ((,class (:foreground "#77713F"))))
   `(tree-sitter-hl-face:variable.special ((,class (:foreground "#77713F"))))
   `(tree-sitter-hl-face:doc ((,class (:foreground "#6D6D69"))))
   `(doom-modeline-bar ((,class (:background "#5E857A"))))
   `(doom-modeline-bar-inactive ((,class (:background "#f2f1ef"))))
   `(doom-modeline-buffer-file ((,class (:foreground "#22262D"))))
   `(doom-modeline-buffer-modified ((,class (:foreground "#77713F"))))
   `(doom-modeline-buffer-path ((,class (:foreground "#4D699B"))))
   `(doom-modeline-buffer-major-mode ((,class (:foreground "#4D699B"))))
   `(doom-modeline-buffer-minor-mode ((,class (:foreground "#6D6D69"))))
   `(doom-modeline-project-dir ((,class (:foreground "#597B75"))))
   `(doom-modeline-project-root-dir ((,class (:foreground "#6D6D69"))))
   `(doom-modeline-info ((,class (:foreground "#6F894E"))))
   `(doom-modeline-warning ((,class (:foreground "#77713f"))))
   `(doom-modeline-urgent ((,class (:foreground "#D7474B"))))
   `(doom-modeline-debug ((,class (:foreground "#6D6D69"))))
   `(doom-modeline-highlight ((,class (:foreground "#4D699B"))))
   `(doom-modeline-panel ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(doom-modeline-notification ((,class (:foreground "#D7474B"))))
   `(doom-modeline-lsp-success ((,class (:foreground "#6F894E"))))
   `(doom-modeline-lsp-warning ((,class (:foreground "#77713f"))))
   `(doom-modeline-lsp-error ((,class (:foreground "#D7474B"))))
   `(doom-modeline-lsp-running ((,class (:foreground "#624C83"))))
   `(doom-modeline-battery-full ((,class (:foreground "#6F894E"))))
   `(doom-modeline-battery-normal ((,class (:foreground "#22262D"))))
   `(doom-modeline-battery-warning ((,class (:foreground "#77713f"))))
   `(doom-modeline-battery-critical ((,class (:foreground "#D7474B"))))
   `(doom-modeline-battery-charging ((,class (:foreground "#4D699B"))))
   `(doom-modeline-evil-normal-state ((,class (:foreground "#4D699B"))))
   `(doom-modeline-evil-insert-state ((,class (:foreground "#6F894E"))))
   `(doom-modeline-evil-visual-state ((,class (:foreground "#624C83"))))
   `(doom-modeline-evil-operator-state ((,class (:foreground "#22262D"))))
   `(doom-modeline-evil-motion-state ((,class (:foreground "#597B75"))))
   `(doom-modeline-evil-replace-state ((,class (:foreground "#D7474B"))))
   `(doom-modeline-evil-emacs-state ((,class (:foreground "#B35B79"))))
   `(doom-modeline-time ((,class (:foreground "#6D6D69"))))
   `(vertico-current ((,class (:background "#e2e1df" :extend t))))
   `(vertico-group-title ((,class (:foreground "#6D6D69"))))
   `(vertico-group-separator ((,class (:foreground "#6D6D69" :strike-through t))))
   `(corfu-default ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(corfu-current ((,class (:background "#e2e1df" :foreground "#22262D"))))
   `(corfu-bar ((,class (:background "#4D699B"))))
   `(corfu-border ((,class (:background "#dddddb"))))
   `(corfu-annotations ((,class (:foreground "#6D6D69"))))
   `(corfu-deprecated ((,class (:foreground "#6D6D69" :strike-through t))))
   `(company-tooltip ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(company-tooltip-selection ((,class (:background "#e2e1df"))))
   `(company-tooltip-common ((,class (:foreground "#4D699B"))))
   `(company-tooltip-common-selection ((,class (:foreground "#4D699B"))))
   `(company-tooltip-annotation ((,class (:foreground "#624C83"))))
   `(company-tooltip-annotation-selection ((,class (:foreground "#624C83"))))
   `(company-tooltip-search ((,class (:background "#77713F" :foreground "#f2f1ef"))))
   `(company-tooltip-search-selection ((,class (:background "#77713F" :foreground "#f2f1ef"))))
   `(company-scrollbar-bg ((,class (:background "#f2f1ef"))))
   `(company-scrollbar-fg ((,class (:background "#4D699B"))))
   `(company-tooltip-scrollbar-thumb ((,class (:background "#4D699B"))))
   `(company-tooltip-scrollbar-track ((,class (:background "#f2f1ef"))))
   `(company-preview ((,class (:foreground "#6D6D69"))))
   `(company-preview-common ((,class (:foreground "#4D699B" :background "#f2f1ef"))))
   `(company-preview-search ((,class (:background "#77713F" :foreground "#f2f1ef"))))
   `(orderless-match-face-0 ((,class (:foreground "#4D699B"))))
   `(orderless-match-face-1 ((,class (:foreground "#6F894E"))))
   `(orderless-match-face-2 ((,class (:foreground "#77713F"))))
   `(orderless-match-face-3 ((,class (:foreground "#B35B79"))))
   `(marginalia-key ((,class (:foreground "#4D699B"))))
   `(marginalia-documentation ((,class (:foreground "#6D6D69"))))
   `(marginalia-file-name ((,class (:foreground "#6D6D69"))))
   `(marginalia-file-priv-dir ((,class (:foreground "#4D699B"))))
   `(marginalia-file-priv-read ((,class (:foreground "#6F894E"))))
   `(marginalia-file-priv-write ((,class (:foreground "#77713F"))))
   `(marginalia-file-priv-exec ((,class (:foreground "#D7474B"))))
   `(marginalia-size ((,class (:foreground "#597B75"))))
   `(marginalia-date ((,class (:foreground "#624C83"))))
   `(marginalia-number ((,class (:foreground "#B35B79"))))
   `(marginalia-mode ((,class (:foreground "#4D699B"))))
   `(marginalia-type ((,class (:foreground "#597B75"))))
   `(consult-file ((,class (:foreground "#22262D"))))
   `(consult-line-number ((,class (:foreground "#9F9F99"))))
   `(consult-bookmark ((,class (:foreground "#4D699B"))))
   `(completions-common-part ((,class (:foreground "#4D699B"))))
   `(completions-first-difference ((,class (:foreground "#B35B79"))))
   `(completions-annotations ((,class (:foreground "#6D6D69"))))
   `(ivy-current-match ((,class (:background "#e2e1df" :foreground "#22262D" :extend t))))
   `(ivy-minibuffer-match-face-1 ((,class (:foreground "#6D6D69"))))
   `(ivy-minibuffer-match-face-2 ((,class (:foreground "#4D699B"))))
   `(ivy-minibuffer-match-face-3 ((,class (:foreground "#6F894E"))))
   `(ivy-minibuffer-match-face-4 ((,class (:foreground "#77713F"))))
   `(ivy-confirm-face ((,class (:foreground "#6F894E"))))
   `(ivy-match-required-face ((,class (:foreground "#D7474B"))))
   `(ivy-virtual ((,class (:foreground "#6D6D69"))))
   `(ivy-highlight-face ((,class (:foreground "#624C83"))))
   `(swiper-match-face-1 ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(swiper-match-face-2 ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(swiper-match-face-3 ((,class (:background "#77713F" :foreground "#f2f1ef"))))
   `(swiper-match-face-4 ((,class (:background "#6F894E" :foreground "#f2f1ef"))))
   `(swiper-line-face ((,class (:background "#e2e1df" :extend t))))
   `(helm-selection ((,class (:background "#e2e1df" :extend t))))
   `(helm-match ((,class (:foreground "#4D699B"))))
   `(helm-source-header ((,class (:background "#f2f1ef" :foreground "#624C83" :extend t))))
   `(helm-header ((,class (:foreground "#22262D" :background "#f2f1ef"))))
   `(helm-candidate-number ((,class (:foreground "#f2f1ef" :background "#4D699B"))))
   `(helm-ff-directory ((,class (:foreground "#4D699B"))))
   `(helm-ff-file ((,class (:foreground "#22262D"))))
   `(helm-ff-executable ((,class (:foreground "#6F894E"))))
   `(helm-ff-symlink ((,class (:foreground "#4d699b"))))
   `(helm-ff-prefix ((,class (:foreground "#f2f1ef" :background "#77713F"))))
   `(helm-buffer-directory ((,class (:foreground "#4D699B"))))
   `(helm-buffer-file ((,class (:foreground "#22262D"))))
   `(helm-buffer-process ((,class (:foreground "#597B75"))))
   `(helm-grep-file ((,class (:foreground "#4D699B"))))
   `(helm-grep-lineno ((,class (:foreground "#9F9F99"))))
   `(helm-grep-match ((,class (:foreground "#77713F"))))
   `(show-paren-match ((,class (:foreground "#4d699b" :background "#f2f1ef"))))
   `(show-paren-match-expression ((,class (:background "#f2f1ef"))))
   `(show-paren-mismatch ((,class (:foreground "#f2f1ef" :background "#D7474B"))))
   `(rainbow-delimiters-depth-1-face ((,class (:foreground "#4D699B"))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground "#6F894E"))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground "#77713F"))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground "#597B75"))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground "#624C83"))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground "#CC6D00"))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground "#B35B79"))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground "#4d699b"))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground "#624c83"))))
   `(rainbow-delimiters-unmatched-face ((,class (:foreground "#D7474B"))))
   `(rainbow-delimiters-mismatched-face ((,class (:foreground "#D7474B"))))
   `(paren-face ((,class (:foreground "#6D6D69"))))
   `(highlight-indent-guides-character-face ((,class (:foreground "#f2f1ef"))))
   `(highlight-indent-guides-top-character-face ((,class (:foreground "#9F9F99"))))
   `(highlight-indent-guides-stack-character-face ((,class (:foreground "#f2f1ef"))))
   `(highlight-indent-guides-even-face ((,class (:background "#f7f7f5"))))
   `(highlight-indent-guides-odd-face ((,class (:background "#f2f1ef"))))
   `(indent-guide-face ((,class (:foreground "#f2f1ef"))))
   `(whitespace-space ((,class (:foreground "#f2f1ef"))))
   `(whitespace-tab ((,class (:foreground "#f2f1ef"))))
   `(whitespace-newline ((,class (:foreground "#f2f1ef"))))
   `(whitespace-trailing ((,class (:background "#D7474B" :foreground "#f2f1ef"))))
   `(whitespace-line ((,class (:background "#f2f1ef" :foreground "#D7474B"))))
   `(whitespace-indentation ((,class (:background "#f2f1ef"))))
   `(whitespace-empty ((,class (:background "#f2f1ef"))))
   `(whitespace-space-after-tab ((,class (:background "#f2f1ef"))))
   `(whitespace-space-before-tab ((,class (:background "#f2f1ef"))))
   `(hl-todo ((,class (:foreground "#D7474B"))))
   `(flycheck-error ((,class (:underline (:style wave :color "#D7474B")))))
   `(flycheck-warning ((,class (:underline (:style wave :color "#77713f")))))
   `(flycheck-info ((,class (:underline (:style wave :color "#6693BF")))))
   `(flycheck-fringe-error ((,class (:foreground "#D7474B"))))
   `(flycheck-fringe-warning ((,class (:foreground "#77713f"))))
   `(flycheck-fringe-info ((,class (:foreground "#6693BF"))))
   `(flycheck-error-list-error ((,class (:foreground "#D7474B"))))
   `(flycheck-error-list-warning ((,class (:foreground "#77713f"))))
   `(flycheck-error-list-info ((,class (:foreground "#6693BF"))))
   `(flycheck-posframe-error-face ((,class (:foreground "#D7474B"))))
   `(flycheck-posframe-warning-face ((,class (:foreground "#77713f"))))
   `(flycheck-posframe-info-face ((,class (:foreground "#6693BF"))))
   `(flycheck-posframe-background-face ((,class (:background "#f2f1ef"))))
   `(flymake-error ((,class (:underline (:style wave :color "#D7474B")))))
   `(flymake-warning ((,class (:underline (:style wave :color "#77713f")))))
   `(flymake-note ((,class (:underline (:style wave :color "#6693BF")))))
   `(flymake-error-echo ((,class (:foreground "#D7474B"))))
   `(flymake-warning-echo ((,class (:foreground "#77713f"))))
   `(flymake-note-echo ((,class (:foreground "#6693BF"))))
   `(compilation-error ((,class (:foreground "#D7474B"))))
   `(compilation-warning ((,class (:foreground "#77713f"))))
   `(compilation-info ((,class (:foreground "#6F894E"))))
   `(compilation-line-number ((,class (:foreground "#9F9F99"))))
   `(compilation-column-number ((,class (:foreground "#9F9F99"))))
   `(compilation-mode-line-exit ((,class (:foreground "#6F894E"))))
   `(compilation-mode-line-fail ((,class (:foreground "#D7474B"))))
   `(compilation-mode-line-run ((,class (:foreground "#77713F"))))
   `(lsp-face-highlight-textual ((,class (:background "#f2f1ef"))))
   `(lsp-face-highlight-read ((,class (:background "#f2f1ef" :underline t))))
   `(lsp-face-highlight-write ((,class (:background "#f2f1ef"))))
   `(lsp-headerline-breadcrumb-path-face ((,class (:foreground "#6D6D69"))))
   `(lsp-headerline-breadcrumb-path-error-face ((,class (:foreground "#D7474B" :underline (:style wave :color "#D7474B")))))
   `(lsp-headerline-breadcrumb-symbols-face ((,class (:foreground "#4D699B"))))
   `(lsp-headerline-breadcrumb-separator-face ((,class (:foreground "#6D6D69"))))
   `(lsp-ui-doc-background ((,class (:background "#f2f1ef"))))
   `(lsp-ui-doc-header ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(lsp-ui-peek-filename ((,class (:foreground "#4D699B"))))
   `(lsp-ui-peek-header ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(lsp-ui-peek-selection ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(lsp-ui-peek-list ((,class (:background "#f7f7f5"))))
   `(lsp-ui-peek-peek ((,class (:background "#f7f7f5"))))
   `(lsp-ui-peek-highlight ((,class (:background "#77713F" :foreground "#f2f1ef"))))
   `(lsp-ui-peek-line-number ((,class (:foreground "#9F9F99"))))
   `(lsp-ui-sideline-code-action ((,class (:foreground "#77713F"))))
   `(lsp-ui-sideline-current-symbol ((,class (:foreground "#22262D"))))
   `(lsp-ui-sideline-symbol ((,class (:foreground "#6D6D69"))))
   `(lsp-ui-sideline-symbol-info ((,class (:foreground "#6D6D69"))))
   `(eglot-highlight-symbol-face ((,class (:background "#f2f1ef"))))
   `(eglot-mode-line ((,class (:foreground "#4D699B"))))
   `(eglot-diagnostic-tag-unnecessary-face ((,class (:foreground "#6D6D69"))))
   `(eglot-diagnostic-tag-deprecated-face ((,class (:foreground "#6D6D69" :strike-through t))))
   `(diff-added ((,class (:background "#dae0d5" :foreground "#6F894E" :extend t))))
   `(diff-removed ((,class (:background "#eee3df" :foreground "#D7474B" :extend t))))
   `(diff-changed ((,class (:background "#eee1c4" :foreground "#77713F" :extend t))))
   `(diff-indicator-added ((,class (:foreground "#6F894E" :background "#dae0d5"))))
   `(diff-indicator-removed ((,class (:foreground "#D7474B" :background "#eee3df"))))
   `(diff-indicator-changed ((,class (:foreground "#77713F" :background "#eee1c4"))))
   `(diff-refine-added ((,class (:background "#cad4c4" :foreground "#6F894E"))))
   `(diff-refine-removed ((,class (:background "#eadad4" :foreground "#D7474B"))))
   `(diff-refine-changed ((,class (:background "#ecd6a7" :foreground "#77713F"))))
   `(diff-header ((,class (:background "#f2f1ef" :foreground "#22262D" :extend t))))
   `(diff-file-header ((,class (:background "#f2f1ef" :foreground "#4D699B" :extend t))))
   `(diff-hunk-header ((,class (:background "#f2f1ef" :foreground "#624C83" :extend t))))
   `(diff-function ((,class (:foreground "#624C83"))))
   `(diff-context ((,class (:foreground "#6D6D69"))))
   `(diff-nonexistent ((,class (:foreground "#6D6D69"))))
   `(smerge-lower ((,class (:background "#dae0d5"))))
   `(smerge-upper ((,class (:background "#eee3df"))))
   `(smerge-base ((,class (:background "#eee1c4"))))
   `(smerge-markers ((,class (:background "#f2f1ef" :foreground "#22262D" :extend t))))
   `(smerge-refined-added ((,class (:background "#cad4c4" :foreground "#6F894E"))))
   `(smerge-refined-removed ((,class (:background "#eadad4" :foreground "#D7474B"))))
   `(diff-hl-insert ((,class (:foreground "#6E915F" :background "#6E915F"))))
   `(diff-hl-delete ((,class (:foreground "#d9a594" :background "#d9a594"))))
   `(diff-hl-change ((,class (:foreground "#DE9800" :background "#DE9800"))))
   `(git-gutter:added ((,class (:foreground "#6E915F"))))
   `(git-gutter:deleted ((,class (:foreground "#d9a594"))))
   `(git-gutter:modified ((,class (:foreground "#DE9800"))))
   `(git-gutter:unchanged ((,class (:background "#f2f1ef"))))
   `(git-gutter-fr:added ((,class (:foreground "#6E915F"))))
   `(git-gutter-fr:deleted ((,class (:foreground "#d9a594"))))
   `(git-gutter-fr:modified ((,class (:foreground "#DE9800"))))
   `(magit-section-heading ((,class (:foreground "#624C83"))))
   `(magit-section-heading-selection ((,class (:foreground "#77713F"))))
   `(magit-section-highlight ((,class (:background "#e2e1df" :extend t))))
   `(magit-section-secondary-heading ((,class (:foreground "#4D699B"))))
   `(magit-diff-added ((,class (:background "#dae0d5" :foreground "#6F894E" :extend t))))
   `(magit-diff-added-highlight ((,class (:background "#cad4c4" :foreground "#6F894E" :extend t))))
   `(magit-diff-removed ((,class (:background "#eee3df" :foreground "#D7474B" :extend t))))
   `(magit-diff-removed-highlight ((,class (:background "#eadad4" :foreground "#D7474B" :extend t))))
   `(magit-diff-context ((,class (:foreground "#6D6D69" :extend t))))
   `(magit-diff-context-highlight ((,class (:background "#f2f1ef" :foreground "#6D6D69" :extend t))))
   `(magit-diff-hunk-heading ((,class (:background "#f2f1ef" :foreground "#22262D" :extend t))))
   `(magit-diff-hunk-heading-highlight ((,class (:background "#f2f1ef" :foreground "#22262D" :extend t))))
   `(magit-diff-hunk-heading-selection ((,class (:background "#f2f1ef" :foreground "#77713F" :extend t))))
   `(magit-diff-file-heading ((,class (:foreground "#22262D"))))
   `(magit-diff-file-heading-highlight ((,class (:background "#e2e1df" :extend t))))
   `(magit-diff-file-heading-selection ((,class (:foreground "#77713F" :background "#e2e1df" :extend t))))
   `(magit-diff-lines-heading ((,class (:background "#77713F" :foreground "#f2f1ef" :extend t))))
   `(magit-diffstat-added ((,class (:foreground "#6F894E"))))
   `(magit-diffstat-removed ((,class (:foreground "#D7474B"))))
   `(magit-branch-local ((,class (:foreground "#4D699B"))))
   `(magit-branch-remote ((,class (:foreground "#6F894E"))))
   `(magit-branch-current ((,class (:foreground "#4d699b" :box (:line-width 1 :color "#4d699b")))))
   `(magit-tag ((,class (:foreground "#77713F"))))
   `(magit-hash ((,class (:foreground "#6D6D69"))))
   `(magit-dimmed ((,class (:foreground "#6D6D69"))))
   `(magit-log-author ((,class (:foreground "#CC6D00"))))
   `(magit-log-date ((,class (:foreground "#6D6D69"))))
   `(magit-log-graph ((,class (:foreground "#6D6D69"))))
   `(magit-process-ng ((,class (:foreground "#D7474B"))))
   `(magit-process-ok ((,class (:foreground "#6F894E"))))
   `(magit-bisect-good ((,class (:foreground "#6F894E"))))
   `(magit-bisect-bad ((,class (:foreground "#D7474B"))))
   `(magit-bisect-skip ((,class (:foreground "#77713F"))))
   `(magit-blame-heading ((,class (:background "#f2f1ef" :foreground "#22262D" :extend t))))
   `(magit-blame-hash ((,class (:foreground "#624C83"))))
   `(magit-blame-name ((,class (:foreground "#CC6D00"))))
   `(magit-blame-date ((,class (:foreground "#6D6D69"))))
   `(magit-blame-summary ((,class (:foreground "#22262D"))))
   `(magit-header-line ((,class (:background "#f2f1ef" :foreground "#624C83" :extend t))))
   `(magit-reflog-commit ((,class (:foreground "#6F894E"))))
   `(magit-reflog-amend ((,class (:foreground "#624C83"))))
   `(magit-reflog-merge ((,class (:foreground "#6F894E"))))
   `(magit-reflog-checkout ((,class (:foreground "#4D699B"))))
   `(magit-reflog-reset ((,class (:foreground "#D7474B"))))
   `(magit-reflog-rebase ((,class (:foreground "#624C83"))))
   `(magit-reflog-cherry-pick ((,class (:foreground "#6F894E"))))
   `(magit-cherry-equivalent ((,class (:foreground "#624C83"))))
   `(magit-cherry-unmatched ((,class (:foreground "#4d699b"))))
   `(git-commit-summary ((,class (:foreground "#22262D"))))
   `(git-commit-overlong-summary ((,class (:foreground "#D7474B"))))
   `(git-commit-nonempty-second-line ((,class (:foreground "#D7474B"))))
   `(git-commit-comment-branch-local ((,class (:foreground "#4D699B"))))
   `(git-commit-comment-branch-remote ((,class (:foreground "#6F894E"))))
   `(git-commit-comment-heading ((,class (:foreground "#624C83"))))
   `(git-commit-comment-file ((,class (:foreground "#4D699B"))))
   `(git-commit-comment-action ((,class (:foreground "#6F894E"))))
   `(transient-key ((,class (:foreground "#4D699B"))))
   `(transient-heading ((,class (:foreground "#624C83"))))
   `(transient-argument ((,class (:foreground "#6F894E"))))
   `(transient-value ((,class (:foreground "#77713F"))))
   `(transient-inactive-value ((,class (:foreground "#6D6D69"))))
   `(transient-inactive-argument ((,class (:foreground "#6D6D69"))))
   `(transient-key-exit ((,class (:foreground "#D7474B"))))
   `(transient-key-stay ((,class (:foreground "#6F894E"))))
   `(transient-key-return ((,class (:foreground "#77713F"))))
   `(org-level-1 ((,class (:foreground "#4D699B"))))
   `(org-level-2 ((,class (:foreground "#624C83"))))
   `(org-level-3 ((,class (:foreground "#597B75"))))
   `(org-level-4 ((,class (:foreground "#6F894E"))))
   `(org-level-5 ((,class (:foreground "#77713F"))))
   `(org-level-6 ((,class (:foreground "#CC6D00"))))
   `(org-level-7 ((,class (:foreground "#B35B79"))))
   `(org-level-8 ((,class (:foreground "#4d699b"))))
   `(org-document-title ((,class (:foreground "#4D699B"))))
   `(org-document-info ((,class (:foreground "#597B75"))))
   `(org-document-info-keyword ((,class (:foreground "#6D6D69"))))
   `(org-headline-done ((,class (:foreground "#6D6D69"))))
   `(org-todo ((,class (:foreground "#D7474B"))))
   `(org-done ((,class (:foreground "#6F894E"))))
   `(org-checkbox ((,class (:foreground "#4D699B"))))
   `(org-checkbox-statistics-todo ((,class (:foreground "#D7474B"))))
   `(org-checkbox-statistics-done ((,class (:foreground "#6F894E"))))
   `(org-block ((,class (:background "#f2f1ef" :foreground "#22262D" :extend t))))
   `(org-block-begin-line ((,class (:background "#f7f7f5" :foreground "#6D6D69" :extend t))))
   `(org-block-end-line ((,class (:background "#f7f7f5" :foreground "#6D6D69" :extend t))))
   `(org-code ((,class (:foreground "#CC6D00"))))
   `(org-verbatim ((,class (:foreground "#6F894E"))))
   `(org-formula ((,class (:foreground "#4d699b"))))
   `(org-table ((,class (:foreground "#4D699B"))))
   `(org-quote ((,class (:foreground "#6D6D69"))))
   `(org-date ((,class (:foreground "#624C83" :underline t))))
   `(org-link ((,class (:foreground "#4D699B" :underline t))))
   `(org-footnote ((,class (:foreground "#4d699b" :underline t))))
   `(org-tag ((,class (:foreground "#6D6D69"))))
   `(org-special-keyword ((,class (:foreground "#624C83"))))
   `(org-drawer ((,class (:foreground "#6D6D69"))))
   `(org-property-value ((,class (:foreground "#597B75"))))
   `(org-priority ((,class (:foreground "#77713F"))))
   `(org-scheduled ((,class (:foreground "#6F894E"))))
   `(org-scheduled-today ((,class (:foreground "#6F894E"))))
   `(org-scheduled-previously ((,class (:foreground "#77713F"))))
   `(org-deadline ((,class (:foreground "#D7474B"))))
   `(org-upcoming-deadline ((,class (:foreground "#CC6D00"))))
   `(org-time-grid ((,class (:foreground "#6D6D69"))))
   `(org-ellipsis ((,class (:foreground "#6D6D69"))))
   `(org-warning ((,class (:foreground "#D7474B"))))
   `(org-agenda-structure ((,class (:foreground "#624C83"))))
   `(org-agenda-date ((,class (:foreground "#4D699B"))))
   `(org-agenda-date-today ((,class (:foreground "#4d699b"))))
   `(org-agenda-date-weekend ((,class (:foreground "#6D6D69"))))
   `(org-agenda-done ((,class (:foreground "#6F894E"))))
   `(org-agenda-current-time ((,class (:foreground "#77713F"))))
   `(org-hide ((,class (:foreground "#f2f1ef"))))
   `(org-indent ((,class (:foreground "#f2f1ef"))))
   `(org-meta-line ((,class (:foreground "#6D6D69"))))
   `(markdown-header-face-1 ((,class (:foreground "#4D699B"))))
   `(markdown-header-face-2 ((,class (:foreground "#624C83"))))
   `(markdown-header-face-3 ((,class (:foreground "#597B75"))))
   `(markdown-header-face-4 ((,class (:foreground "#6F894E"))))
   `(markdown-header-face-5 ((,class (:foreground "#77713F"))))
   `(markdown-header-face-6 ((,class (:foreground "#CC6D00"))))
   `(markdown-header-delimiter-face ((,class (:foreground "#6D6D69"))))
   `(markdown-code-face ((,class (:background "#f2f1ef" :foreground "#22262D" :extend t))))
   `(markdown-inline-code-face ((,class (:foreground "#CC6D00" :background "#f2f1ef"))))
   `(markdown-pre-face ((,class (:background "#f2f1ef" :foreground "#6F894E" :extend t))))
   `(markdown-link-face ((,class (:foreground "#4D699B" :underline t))))
   `(markdown-url-face ((,class (:foreground "#4d699b"))))
   `(markdown-link-title-face ((,class (:foreground "#6D6D69"))))
   `(markdown-reference-face ((,class (:foreground "#6D6D69"))))
   `(markdown-footnote-marker-face ((,class (:foreground "#4d699b"))))
   `(markdown-list-face ((,class (:foreground "#624C83"))))
   `(markdown-markup-face ((,class (:foreground "#6D6D69"))))
   `(markdown-bold-face ((,class (:foreground "#22262D"))))
   `(markdown-italic-face ((,class (:foreground "#22262D"))))
   `(markdown-blockquote-face ((,class (:foreground "#6D6D69"))))
   `(markdown-metadata-key-face ((,class (:foreground "#624C83"))))
   `(markdown-metadata-value-face ((,class (:foreground "#6F894E"))))
   `(markdown-gfm-checkbox-face ((,class (:foreground "#4D699B"))))
   `(markdown-table-face ((,class (:foreground "#4D699B"))))
   `(markdown-language-keyword-face ((,class (:foreground "#6D6D69"))))
   `(dired-directory ((,class (:foreground "#4D699B"))))
   `(dired-header ((,class (:foreground "#624C83"))))
   `(dired-flagged ((,class (:foreground "#D7474B"))))
   `(dired-mark ((,class (:foreground "#77713F"))))
   `(dired-marked ((,class (:foreground "#77713F"))))
   `(dired-perm-write ((,class (:foreground "#CC6D00"))))
   `(dired-symlink ((,class (:foreground "#4d699b"))))
   `(dired-broken-symlink ((,class (:foreground "#D7474B" :underline t))))
   `(dired-ignored ((,class (:foreground "#6D6D69"))))
   `(dired-special ((,class (:foreground "#77713F"))))
   `(dired-warning ((,class (:foreground "#77713f"))))
   `(diredfl-dir-name ((,class (:foreground "#4D699B"))))
   `(diredfl-dir-heading ((,class (:foreground "#624C83"))))
   `(diredfl-file-name ((,class (:foreground "#22262D"))))
   `(diredfl-file-suffix ((,class (:foreground "#6D6D69"))))
   `(diredfl-symlink ((,class (:foreground "#4d699b"))))
   `(diredfl-number ((,class (:foreground "#B35B79"))))
   `(diredfl-date-time ((,class (:foreground "#624C83"))))
   `(diredfl-no-priv ((,class (:foreground "#6D6D69"))))
   `(diredfl-dir-priv ((,class (:foreground "#4D699B"))))
   `(diredfl-read-priv ((,class (:foreground "#6F894E"))))
   `(diredfl-write-priv ((,class (:foreground "#77713F"))))
   `(diredfl-exec-priv ((,class (:foreground "#D7474B"))))
   `(diredfl-flag-mark-line ((,class (:background "#e2e1df" :extend t))))
   `(diredfl-flag-mark ((,class (:foreground "#77713F" :background "#e2e1df"))))
   `(diredfl-deletion ((,class (:foreground "#D7474B" :background "#eee3df"))))
   `(diredfl-deletion-file-name ((,class (:foreground "#D7474B"))))
   `(diredfl-compressed-file-name ((,class (:foreground "#CC6D00"))))
   `(diredfl-compressed-file-suffix ((,class (:foreground "#CC6D00"))))
   `(diredfl-ignored-file-name ((,class (:foreground "#6D6D69"))))
   `(which-key-key-face ((,class (:foreground "#4D699B"))))
   `(which-key-group-description-face ((,class (:foreground "#624C83"))))
   `(which-key-command-description-face ((,class (:foreground "#22262D"))))
   `(which-key-local-map-description-face ((,class (:foreground "#597B75"))))
   `(which-key-separator-face ((,class (:foreground "#6D6D69"))))
   `(which-key-note-face ((,class (:foreground "#6D6D69"))))
   `(tab-bar ((,class (:background "#f2f1ef" :foreground "#6D6D69"))))
   `(tab-bar-tab ((,class (:background "#f2f1ef" :foreground "#22262D" :box (:line-width -1 :color "#f2f1ef")))))
   `(tab-bar-tab-inactive ((,class (:background "#f2f1ef" :foreground "#6D6D69"))))
   `(tab-bar-tab-group-current ((,class (:foreground "#4D699B"))))
   `(tab-bar-tab-group-inactive ((,class (:foreground "#6D6D69"))))
   `(tab-line ((,class (:background "#f2f1ef" :foreground "#6D6D69"))))
   `(tab-line-tab ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(tab-line-tab-current ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(tab-line-tab-inactive ((,class (:background "#f2f1ef" :foreground "#6D6D69"))))
   `(tab-line-highlight ((,class (:background "#f2f1ef" :foreground "#4D699B"))))
   `(centaur-tabs-default ((,class (:background "#f2f1ef" :foreground "#6D6D69"))))
   `(centaur-tabs-selected ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(centaur-tabs-unselected ((,class (:background "#f2f1ef" :foreground "#6D6D69"))))
   `(centaur-tabs-selected-modified ((,class (:background "#f2f1ef" :foreground "#77713F"))))
   `(centaur-tabs-unselected-modified ((,class (:background "#f2f1ef" :foreground "#77713F"))))
   `(centaur-tabs-active-bar-face ((,class (:background "#4D699B"))))
   `(centaur-tabs-modified-marker-selected ((,class (:foreground "#77713F" :background "#f2f1ef"))))
   `(centaur-tabs-modified-marker-unselected ((,class (:foreground "#77713F" :background "#f2f1ef"))))
   `(evil-ex-info ((,class (:foreground "#D7474B"))))
   `(evil-ex-substitute-matches ((,class (:background "#eee3df" :foreground "#D7474B" :strike-through t))))
   `(evil-ex-substitute-replacement ((,class (:background "#dae0d5" :foreground "#6F894E" :underline t))))
   `(evil-ex-lazy-highlight ((,class (:background "#9fb5c9" :foreground "#22262D"))))
   `(evil-search-highlight-persist-highlight-face ((,class (:background "#9fb5c9"))))
   `(evil-goggles-default-face ((,class (:background "#f2f1ef"))))
   `(avy-lead-face ((,class (:background "#D7474B" :foreground "#f2f1ef"))))
   `(avy-lead-face-0 ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(avy-lead-face-1 ((,class (:background "#6D6D69" :foreground "#f2f1ef"))))
   `(avy-lead-face-2 ((,class (:background "#624C83" :foreground "#f2f1ef"))))
   `(avy-background-face ((,class (:foreground "#6D6D69"))))
   `(aw-leading-char-face ((,class (:foreground "#D7474B" :height 2.0))))
   `(aw-background-face ((,class (:foreground "#6D6D69"))))
   `(hydra-face-red ((,class (:foreground "#D7474B"))))
   `(hydra-face-blue ((,class (:foreground "#4D699B"))))
   `(hydra-face-amaranth ((,class (:foreground "#B35B79"))))
   `(hydra-face-pink ((,class (:foreground "#624c83"))))
   `(hydra-face-teal ((,class (:foreground "#597B75"))))
   `(symbol-overlay-default-face ((,class (:background "#f2f1ef" :underline t))))
   `(anzu-mode-line ((,class (:foreground "#624C83"))))
   `(anzu-mode-line-no-match ((,class (:foreground "#D7474B"))))
   `(anzu-match-1 ((,class (:background "#6F894E" :foreground "#f2f1ef"))))
   `(anzu-match-2 ((,class (:background "#77713F" :foreground "#f2f1ef"))))
   `(anzu-match-3 ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(highlight-numbers-number ((,class (:foreground "#B35B79"))))
   `(highlight-quoted-symbol ((,class (:foreground "#597B75"))))
   `(highlight-quoted-string ((,class (:foreground "#6F894E"))))
   `(highlight-symbol-face ((,class (:background "#f2f1ef"))))
   `(hi-yellow ((,class (:background "#77713F" :foreground "#f2f1ef"))))
   `(hi-green ((,class (:background "#6F894E" :foreground "#f2f1ef"))))
   `(hi-blue ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(hi-pink ((,class (:background "#624c83" :foreground "#f2f1ef"))))
   `(hi-red-b ((,class (:foreground "#D7474B"))))
   `(term ((,class (:foreground "#22262D" :background "#f2f1ef"))))
   `(term-color-black ((,class (:foreground "#22262D" :background "#22262D"))))
   `(term-color-red ((,class (:foreground "#c84053" :background "#c84053"))))
   `(term-color-green ((,class (:foreground "#6f894e" :background "#6f894e"))))
   `(term-color-yellow ((,class (:foreground "#77713f" :background "#77713f"))))
   `(term-color-blue ((,class (:foreground "#4d699b" :background "#4d699b"))))
   `(term-color-magenta ((,class (:foreground "#766b90" :background "#766b90"))))
   `(term-color-cyan ((,class (:foreground "#597b75" :background "#597b75"))))
   `(term-color-white ((,class (:foreground "#e2e1df" :background "#e2e1df"))))
   `(term-color-bright-black ((,class (:foreground "#22262D" :background "#22262D"))))
   `(term-color-bright-red ((,class (:foreground "#e82424" :background "#e82424"))))
   `(term-color-bright-green ((,class (:foreground "#6e915f" :background "#6e915f"))))
   `(term-color-bright-yellow ((,class (:foreground "#de9800" :background "#de9800"))))
   `(term-color-bright-blue ((,class (:foreground "#4d699b" :background "#4d699b"))))
   `(term-color-bright-magenta ((,class (:foreground "#624c83" :background "#624c83"))))
   `(term-color-bright-cyan ((,class (:foreground "#4e8ca2" :background "#4e8ca2"))))
   `(term-color-bright-white ((,class (:foreground "#f2f1ef" :background "#f2f1ef"))))
   `(vterm-color-black ((,class (:foreground "#22262D" :background "#22262D"))))
   `(vterm-color-red ((,class (:foreground "#c84053" :background "#e82424"))))
   `(vterm-color-green ((,class (:foreground "#6f894e" :background "#6e915f"))))
   `(vterm-color-yellow ((,class (:foreground "#77713f" :background "#de9800"))))
   `(vterm-color-blue ((,class (:foreground "#4d699b" :background "#4d699b"))))
   `(vterm-color-magenta ((,class (:foreground "#766b90" :background "#624c83"))))
   `(vterm-color-cyan ((,class (:foreground "#597b75" :background "#4e8ca2"))))
   `(vterm-color-white ((,class (:foreground "#e2e1df" :background "#f2f1ef"))))
   `(eshell-prompt ((,class (:foreground "#624C83"))))
   `(eshell-ls-directory ((,class (:foreground "#4D699B"))))
   `(eshell-ls-symlink ((,class (:foreground "#4d699b"))))
   `(eshell-ls-executable ((,class (:foreground "#6F894E"))))
   `(eshell-ls-archive ((,class (:foreground "#B35B79"))))
   `(eshell-ls-backup ((,class (:foreground "#6D6D69"))))
   `(eshell-ls-clutter ((,class (:foreground "#6D6D69"))))
   `(eshell-ls-missing ((,class (:foreground "#D7474B"))))
   `(eshell-ls-product ((,class (:foreground "#77713F"))))
   `(eshell-ls-readonly ((,class (:foreground "#CC6D00"))))
   `(eshell-ls-special ((,class (:foreground "#624C83"))))
   `(eshell-ls-unreadable ((,class (:foreground "#6D6D69"))))
   `(solaire-default-face ((,class (:background "#f7f7f5" :foreground "#22262D"))))
   `(solaire-hl-line-face ((,class (:background "#e2e1df" :extend t))))
   `(solaire-mode-line-face ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(solaire-mode-line-inactive-face ((,class (:background "#f2f1ef" :foreground "#6D6D69"))))
   `(nav-flash-face ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(pulse-highlight-start-face ((,class (:background "#4D699B"))))
   `(ivy-posframe ((,class (:background "#f2f1ef" :foreground "#22262D"))))
   `(ivy-posframe-border ((,class (:background "#dddddb"))))
   `(info-title-1 ((,class (:foreground "#4D699B"))))
   `(info-title-2 ((,class (:foreground "#624C83"))))
   `(info-title-3 ((,class (:foreground "#597B75"))))
   `(info-title-4 ((,class (:foreground "#6F894E"))))
   `(info-menu-header ((,class (:foreground "#624C83"))))
   `(info-menu-star ((,class (:foreground "#D7474B"))))
   `(info-node ((,class (:foreground "#4D699B"))))
   `(shr-h1 ((,class (:foreground "#4D699B"))))
   `(shr-h2 ((,class (:foreground "#624C83"))))
   `(shr-h3 ((,class (:foreground "#597B75"))))
   `(shr-h4 ((,class (:foreground "#6F894E"))))
   `(shr-link ((,class (:foreground "#4D699B" :underline t))))
   `(shr-code ((,class (:foreground "#CC6D00" :background "#f2f1ef"))))
   `(shr-selected-link ((,class (:background "#4D699B" :foreground "#f2f1ef"))))
   `(message-header-name ((,class (:foreground "#624C83"))))
   `(message-header-to ((,class (:foreground "#22262D"))))
   `(message-header-cc ((,class (:foreground "#6D6D69"))))
   `(message-header-subject ((,class (:foreground "#4D699B"))))
   `(message-header-other ((,class (:foreground "#597B75"))))
   `(message-header-newsgroups ((,class (:foreground "#77713F"))))
   `(message-header-xheader ((,class (:foreground "#6D6D69"))))
   `(message-separator ((,class (:foreground "#6D6D69"))))
   `(message-cited-text ((,class (:foreground "#6D6D69"))))
   `(message-cited-text-1 ((,class (:foreground "#6D6D69"))))
   `(message-cited-text-2 ((,class (:foreground "#6F894E"))))
   `(message-cited-text-3 ((,class (:foreground "#77713F"))))
   `(message-cited-text-4 ((,class (:foreground "#CC6D00"))))
   `(message-mml ((,class (:foreground "#6F894E"))))
   `(outline-1 ((,class (:foreground "#4D699B"))))
   `(outline-2 ((,class (:foreground "#624C83"))))
   `(outline-3 ((,class (:foreground "#597B75"))))
   `(outline-4 ((,class (:foreground "#6F894E"))))
   `(outline-5 ((,class (:foreground "#77713F"))))
   `(outline-6 ((,class (:foreground "#CC6D00"))))
   `(outline-7 ((,class (:foreground "#B35B79"))))
   `(outline-8 ((,class (:foreground "#4d699b")))))

  (custom-theme-set-variables
   'kanso-pearl
   `(ansi-color-names-vector
     ["#22262D" "#c84053" "#6f894e" "#77713f"
      "#4d699b" "#766b90" "#597b75" "#e2e1df"])))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'kanso-pearl)
(provide 'kanso-pearl-theme)
;;; kanso-pearl-theme.el ends here
