;;; kujukuju-theme.el --- Kujukuju dark theme -*- lexical-binding: t; -*-
;;
;; Ported from the Kujukuju Neovim colourscheme
;; (itself ported from focus-editor: https://github.com/focus-editor/focus)
;;
;; Supports: Doom Emacs, doom-modeline, LSP (lsp-mode / eglot),
;;           treesit / tree-sitter, Magit, Company, Vertico, Corfu,
;;           rainbow-delimiters, which-key, org-mode.
;;
;; Installation (Doom Emacs):
;;   1. Place this file in ~/.doom.d/themes/
;;   2. In ~/.doom.d/config.el add:
;;        (setq doom-theme 'kujukuju)

;;; Code:

(require 'doom-themes)

(defgroup kujukuju-theme nil
  "Options for the Kujukuju theme."
  :group 'doom-themes)

(def-doom-theme kujukuju
  "A dark theme ported from the Kujukuju Neovim colourscheme."

  ;; ── Palette ────────────────────────────────────────────────────────────────
  ;; (NAME      GUI           256           16)
  ((bg         '("#050505"   "black"       "black"      ))
   (bg-alt     '("#080B14"   "black"       "black"      ))
   (base0      '("#080B14"   "black"       "black"      ))
   (base1      '("#191C25"   "#1c1c1c"     "brightblack"))
   (base2      '("#21333F"   "#262626"     "brightblack"))
   (base3      '("#1A3C49"   "#303030"     "brightblack"))
   (base4      '("#1A3B49"   "#3a3a3a"     "brightblack"))
   (base5      '("#87919D"   "#585858"     "brightblack"))
   (base6      '("#CBCEBC"   "#bcbcbc"     "white"      ))
   (base7      '("#E8FCFE"   "#e4e4e4"     "white"      ))
   (base8      '("#FFFFFF"   "#ffffff"     "white"      ))
   (fg         '("#CBCEBC"   "#bcbcbc"     "white"      ))
   (fg-alt     '("#87919D"   "#585858"     "white"      ))

   ;; Required doom-themes base colour slots
   (grey        '("#87919D"  "#585858"     "brightblack"  ))
   (red         '("#FF6A6A"  "#ff5f5f"     "red"          ))
   (orange      '("#FF6A27"  "#ff5f00"     "brightred"    ))
   (yellow      '("#E4D97D"  "#d7d75f"     "yellow"       ))
   (green       '("#33B333"  "#00af00"     "green"        ))
   (teal        '("#599999"  "#5fafaf"     "brightcyan"   ))
   (blue        '("#26B2B2"  "#00afaf"     "cyan"         ))
   (dark-blue   '("#1A3C49"  "#005f5f"     "blue"         ))
   (magenta     '("#F07178"  "#ff5f5f"     "magenta"      ))
   (violet      '("#FFA759"  "#ffaf5f"     "brightmagenta"))
   (cyan        '("#9DD2BB"  "#87d7af"     "cyan"         ))
   (dark-cyan   '("#599999"  "#5fafaf"     "brightcyan"   ))

   ;; Required doom-themes semantic slots (used by doom-themes-base.el)
   (highlight    '("#1A3C49"  "#005f5f"     "blue"         ))
   (vertical-bar '("#21333F"  "#262626"     "brightblack"  ))
   (selection    '("#1A3C49"  "#005f5f"     "blue"         ))
   (builtin      '("#E0AD82"  "#d7af5f"     "yellow"       ))
   (comments     '("#87919D"  "#585858"     "brightblack"  ))
   (doc-comments '("#87919D"  "#585858"     "brightblack"  ))
   (constants    '("#FF6A27"  "#ff5f00"     "brightred"    ))
   (functions    '("#FFCC66"  "#ffd75f"     "brightyellow" ))
   (keywords     '("#F07178"  "#ff5f5f"     "magenta"      ))
   (methods      '("#FFCC66"  "#ffd75f"     "brightyellow" ))
   (operators    '("#F07178"  "#ff5f5f"     "magenta"      ))
   (type         '("#FFA759"  "#ffaf5f"     "brightmagenta"))
   (strings      '("#BAE67E"  "#afd75f"     "green"        ))
   (variables    '("#CBCEBC"  "#bcbcbc"     "white"        ))
   (numbers      '("#9DD2BB"  "#87d7af"     "cyan"         ))
   (region       '("#1A3C49"  "#005f5f"     "blue"         ))
   (error        '("#FF0000"  "#ff0000"     "red"          ))
   (warning      '("#E4D97D"  "#d7d75f"     "yellow"       ))
   (success      '("#33B333"  "#00af00"     "green"        ))
   (vc-modified  '("#E4D97D"  "#d7d75f"     "yellow"       ))
   (vc-added     '("#33B333"  "#00af00"     "green"        ))
   (vc-deleted   '("#FF6A6A"  "#ff5f5f"     "red"          ))

   ;; Kujukuju-specific aliases (all defined as palette entries so Doom
   ;; can resolve them by name in face specs)
   (kuju-fg        '("#CBCEBC" "#bcbcbc"  "white"        ))
   (kuju-fg-dim    '("#CBCEBC" "#bcbcbc"  "white"        ))
   (kuju-fg-dim2   '("#87919D" "#585858"  "brightblack"  ))
   (kuju-comment   '("#87919D" "#585858"  "brightblack"  ))
   (kuju-gutter    '("#E0AD82" "#d7af5f"  "yellow"       ))
   (kuju-border    '("#21333F" "#262626"  "brightblack"  ))
   (kuju-cursor    '("#FFA717" "#ffaf00"  "yellow"       ))
   (kuju-cursorline '("#191C25" "#1c1c1c" "brightblack"  ))
   (kuju-sel-act   '("#1A3C49" "#005f5f"  "blue"         ))
   (kuju-sel-inact '("#1A3B49" "#005f5f"  "blue"         ))
   (kuju-search    '("#8E772E" "#875f00"  "yellow"       ))
   (kuju-bracket   '("#E8FCFE" "#e4e4e4"  "white"        ))
   (kuju-accent    '("#599999" "#5fafaf"  "cyan"         ))
   (kuju-string    '("#BAE67E" "#afd75f"  "green"        ))
   (kuju-number    '("#9DD2BB" "#87d7af"  "cyan"         ))
   (kuju-value     '("#FF6A27" "#ff5f00"  "brightred"    ))
   (kuju-keyword   '("#F07178" "#ff5f5f"  "magenta"      ))
   (kuju-punct     '("#CBCEBC" "#bcbcbc"  "white"        ))
   (kuju-type      '("#FFA759" "#ffaf5f"  "brightmagenta"))
   (kuju-func      '("#FFCC66" "#ffd75f"  "brightyellow" ))
   (kuju-macro     '("#E0AD82" "#d7af5f"  "yellow"       ))
   (kuju-directive '("#FFA759" "#ffaf5f"  "brightmagenta"))
   (kuju-builtin-v '("#9DD2BB" "#87d7af"  "cyan"         ))
   (kuju-builtin-f '("#E0AD82" "#d7af5f"  "yellow"       ))
   (kuju-err       '("#FF0000" "#ff0000"  "red"          ))
   (kuju-warn      '("#E4D97D" "#d7d75f"  "yellow"       ))
   (kuju-ok        '("#33B333" "#00af00"  "green"        ))
   (kuju-heading1  '("#FFA759" "#ffaf5f"  "brightmagenta"))
   (kuju-heading2  '("#E0AD82" "#d7af5f"  "yellow"       )))

  ;; ── Face definitions ───────────────────────────────────────────────────────
  (
   ;; ── Core editor ──────────────────────────────────────────────────────────
   (default                        :foreground kuju-fg       :background bg)
   (fringe                         :foreground kuju-gutter   :background bg)
   (vertical-border                :foreground kuju-border)
   (window-divider                 :foreground kuju-border)
   (window-divider-first-pixel     :foreground kuju-border)
   (window-divider-last-pixel      :foreground kuju-border)
   (border                         :foreground kuju-border)
   (cursor                         :background kuju-cursor   :foreground "#202020")
   (hl-line                        :background kuju-cursorline)
   (region                         :background kuju-sel-act  :extend t)
   (secondary-selection            :background kuju-sel-inact :extend t)
   (highlight                      :background kuju-sel-act)
   (lazy-highlight                 :background kuju-search   :foreground bg)
   (isearch                        :background kuju-search   :foreground bg)
   (isearch-fail                   :foreground kuju-err     )
   (replace-highlight              :background kuju-err      :foreground bg)
   (match                          :foreground kuju-accent  )
   (show-paren-match               :foreground kuju-bracket  :underline t)
   (show-paren-mismatch            :foreground kuju-err     )
   (trailing-whitespace            :background kuju-err)
   (whitespace-trailing            :background kuju-err)
   (whitespace-tab                 :foreground kuju-gutter)
   (whitespace-space               :foreground kuju-gutter)
   (escape-glyph                   :foreground kuju-string)
   (minibuffer-prompt              :foreground kuju-accent  )

   ;; ── Line numbers ─────────────────────────────────────────────────────────
   (line-number                    :foreground kuju-gutter   :background bg)
   (line-number-current-line       :foreground kuju-fg-dim   :background kuju-cursorline)
   (line-number-major-tick         :foreground kuju-gutter   :background bg)
   (line-number-minor-tick         :foreground kuju-gutter   :background bg)

   ;; ── Modeline (built-in) ──────────────────────────────────────────────────
   (mode-line                      :foreground kuju-fg-dim   :background bg-alt)
   (mode-line-inactive             :foreground kuju-fg-dim2  :background bg-alt)
   (mode-line-buffer-id            :foreground kuju-fg      )
   (mode-line-emphasis             :foreground kuju-accent)
   (mode-line-highlight            :foreground kuju-func)

   ;; ── doom-modeline ────────────────────────────────────────────────────────
   (doom-modeline-bar                :background kuju-accent)
   (doom-modeline-bar-inactive       :background kuju-border)
   (doom-modeline-buffer-file        :foreground kuju-fg     )
   (doom-modeline-buffer-modified    :foreground kuju-warn   )
   (doom-modeline-buffer-major-mode  :foreground kuju-accent )
   (doom-modeline-buffer-minor-mode  :foreground kuju-fg-dim2)
   (doom-modeline-project-dir        :foreground kuju-gutter)
   (doom-modeline-project-root-dir   :foreground kuju-gutter)
   (doom-modeline-info               :foreground kuju-ok)
   (doom-modeline-warning            :foreground kuju-warn)
   (doom-modeline-urgent             :foreground kuju-err)
   (doom-modeline-error              :foreground kuju-err)
   (doom-modeline-lsp-success        :foreground kuju-ok)
   (doom-modeline-lsp-warning        :foreground kuju-warn)
   (doom-modeline-lsp-error          :foreground kuju-err)
   (doom-modeline-input-method       :foreground kuju-accent)
   (doom-modeline-debug              :foreground kuju-warn)
   (doom-modeline-evil-normal-state  :foreground kuju-accent)
   (doom-modeline-evil-insert-state  :foreground kuju-ok)
   (doom-modeline-evil-visual-state  :foreground kuju-type)
   (doom-modeline-evil-replace-state :foreground kuju-keyword)
   (doom-modeline-evil-operator-state :foreground kuju-func)
   (doom-modeline-evil-motion-state  :foreground kuju-builtin-v)
   (doom-modeline-evil-emacs-state   :foreground kuju-macro)

   ;; ── Font lock (classic syntax) ───────────────────────────────────────────
   (font-lock-comment-face           :foreground kuju-comment )
   (font-lock-comment-delimiter-face :foreground kuju-comment )
   (font-lock-doc-face               :foreground kuju-comment )
   (font-lock-doc-markup-face        :foreground kuju-comment)
   (font-lock-string-face            :foreground kuju-string)
   (font-lock-regexp-grouping-backslash :foreground kuju-string)
   (font-lock-regexp-grouping-construct :foreground kuju-value)
   (font-lock-number-face            :foreground kuju-number)
   (font-lock-constant-face          :foreground kuju-value)
   (font-lock-builtin-face           :foreground kuju-builtin-f)
   (font-lock-keyword-face           :foreground kuju-keyword)
   (font-lock-operator-face          :foreground kuju-keyword)
   (font-lock-type-face              :foreground kuju-type)
   (font-lock-function-name-face     :foreground kuju-func)
   (font-lock-function-call-face     :foreground kuju-func)
   (font-lock-variable-name-face     :foreground kuju-fg)
   (font-lock-variable-use-face      :foreground kuju-fg)
   (font-lock-property-name-face     :foreground kuju-fg)
   (font-lock-property-use-face      :foreground kuju-fg)
   (font-lock-preprocessor-face      :foreground kuju-directive)
   (font-lock-negation-char-face     :foreground kuju-keyword)
   (font-lock-warning-face           :foreground kuju-warn)
   (font-lock-misc-punctuation-face  :foreground kuju-punct)
   (font-lock-bracket-face           :foreground kuju-punct)
   (font-lock-delimiter-face         :foreground kuju-punct)
   (font-lock-punctuation-face       :foreground kuju-punct)
   (font-lock-escape-face            :foreground kuju-string)

   ;; ── Tree-sitter (treesit built-in, Emacs 29+) ────────────────────────────
   (treesit-fold-replacement-face    :foreground kuju-fg-dim2  :background bg-alt)

   ;; ── tree-sitter (tree-sitter.el package) ─────────────────────────────────
   (tree-sitter-hl-face:comment          :foreground kuju-comment )
   (tree-sitter-hl-face:doc              :foreground kuju-comment )
   (tree-sitter-hl-face:string           :foreground kuju-string)
   (tree-sitter-hl-face:string.special   :foreground kuju-string)
   (tree-sitter-hl-face:escape           :foreground kuju-string)
   (tree-sitter-hl-face:embedded         :foreground kuju-value)
   (tree-sitter-hl-face:number           :foreground kuju-number)
   (tree-sitter-hl-face:constant         :foreground kuju-value)
   (tree-sitter-hl-face:constant.builtin :foreground kuju-value)
   (tree-sitter-hl-face:keyword          :foreground kuju-keyword)
   (tree-sitter-hl-face:keyword.special  :foreground kuju-keyword)
   (tree-sitter-hl-face:operator         :foreground kuju-keyword)
   (tree-sitter-hl-face:punctuation              :foreground kuju-punct)
   (tree-sitter-hl-face:punctuation.bracket      :foreground kuju-punct)
   (tree-sitter-hl-face:punctuation.delimiter    :foreground kuju-punct)
   (tree-sitter-hl-face:punctuation.special      :foreground kuju-string)
   (tree-sitter-hl-face:type             :foreground kuju-type)
   (tree-sitter-hl-face:type.builtin     :foreground kuju-type)
   (tree-sitter-hl-face:type.super       :foreground kuju-type)
   (tree-sitter-hl-face:type.argument    :foreground kuju-type)
   (tree-sitter-hl-face:type.parameter   :foreground kuju-type)
   (tree-sitter-hl-face:constructor      :foreground kuju-type)
   (tree-sitter-hl-face:function         :foreground kuju-func)
   (tree-sitter-hl-face:function.call    :foreground kuju-func)
   (tree-sitter-hl-face:function.builtin :foreground kuju-builtin-f)
   (tree-sitter-hl-face:function.macro   :foreground kuju-macro)
   (tree-sitter-hl-face:function.special :foreground kuju-func)
   (tree-sitter-hl-face:method           :foreground kuju-func)
   (tree-sitter-hl-face:method.call      :foreground kuju-func)
   (tree-sitter-hl-face:variable         :foreground kuju-fg)
   (tree-sitter-hl-face:variable.builtin :foreground kuju-builtin-v)
   (tree-sitter-hl-face:variable.parameter  :foreground kuju-fg)
   (tree-sitter-hl-face:variable.special    :foreground kuju-builtin-v)
   (tree-sitter-hl-face:field             :foreground kuju-fg)
   (tree-sitter-hl-face:property          :foreground kuju-fg)
   (tree-sitter-hl-face:property.definition :foreground kuju-fg)
   (tree-sitter-hl-face:attribute         :foreground kuju-directive)
   (tree-sitter-hl-face:label             :foreground kuju-keyword)
   (tree-sitter-hl-face:namespace         :foreground kuju-type)
   (tree-sitter-hl-face:module            :foreground kuju-type)
   (tree-sitter-hl-face:tag               :foreground kuju-type)
   (tree-sitter-hl-face:tag.attribute     :foreground kuju-directive)
   (tree-sitter-hl-face:tag.delimiter     :foreground kuju-punct)

   ;; ── LSP (lsp-mode) ───────────────────────────────────────────────────────
   (lsp-face-highlight-textual          :background kuju-sel-inact :extend t)
   (lsp-face-highlight-read             :background kuju-sel-inact :extend t)
   (lsp-face-highlight-write            :background kuju-sel-act   :extend t)
   (lsp-ui-doc-background               :background bg-alt)
   (lsp-ui-doc-header                   :foreground kuju-accent    :background bg-alt)
   (lsp-ui-peek-filename                :foreground kuju-accent)
   (lsp-ui-peek-header                  :foreground kuju-fg        :background kuju-sel-act)
   (lsp-ui-peek-selection               :foreground kuju-fg        :background kuju-sel-act)
   (lsp-ui-peek-list                    :background bg-alt)
   (lsp-ui-peek-peek                    :background bg-alt)
   (lsp-ui-peek-highlight               :background kuju-search)
   (lsp-ui-peek-line-number             :foreground kuju-gutter)
   (lsp-ui-sideline-code-action         :foreground kuju-warn)
   (lsp-ui-sideline-current-symbol      :foreground kuju-accent)
   (lsp-ui-sideline-symbol-info         :foreground kuju-fg-dim2)
   (lsp-inlay-hint-face                 :foreground kuju-gutter    :background bg-alt)
   (lsp-inlay-hint-type-face            :foreground kuju-gutter    :background bg-alt)
   (lsp-headerline-breadcrumb-path-face :foreground kuju-fg-dim2)
   (lsp-headerline-breadcrumb-symbols-face :foreground kuju-accent)
   (lsp-headerline-breadcrumb-separator-face :foreground kuju-border)
   (lsp-lens-face                       :foreground kuju-gutter)
   (lsp-lens-mouse-face                 :foreground kuju-accent    :underline t)

   ;; ── Eglot ────────────────────────────────────────────────────────────────
   (eglot-highlight-symbol-face         :background kuju-sel-act   :extend t)
   (eglot-inlay-hint-face               :foreground kuju-gutter    :background bg-alt)
   (eglot-diagnostic-tag-unnecessary-face :foreground kuju-fg-dim2 :underline t)

   ;; ── Diagnostics (flymake + flycheck) ─────────────────────────────────────
   (flymake-error                       :underline `(:style wave :color "#FF0000"))
   (flymake-warning                     :underline `(:style wave :color "#E4D97D"))
   (flymake-note                        :underline `(:style wave :color "#599999"))
   (flycheck-error                      :underline `(:style wave :color "#FF0000"))
   (flycheck-warning                    :underline `(:style wave :color "#E4D97D"))
   (flycheck-info                       :underline `(:style wave :color "#599999"))
   (flycheck-fringe-error               :foreground kuju-err       :background bg)
   (flycheck-fringe-warning             :foreground kuju-warn      :background bg)
   (flycheck-fringe-info                :foreground kuju-accent    :background bg)

   (error                               :foreground kuju-err      )
   (warning                             :foreground kuju-warn     )
   (success                             :foreground kuju-ok       )

   ;; ── Diff ─────────────────────────────────────────────────────────────────
   (diff-header                         :foreground kuju-fg-dim2   :background bg-alt)
   (diff-file-header                    :foreground kuju-accent    :background bg-alt)
   (diff-added                          :foreground kuju-ok        :background bg-alt :extend t)
   (diff-removed                        :foreground kuju-err       :background bg-alt :extend t)
   (diff-changed                        :foreground kuju-warn      :background bg-alt :extend t)
   (diff-refine-added                   :foreground kuju-ok        :background kuju-sel-act   :extend t)
   (diff-refine-removed                 :foreground kuju-err       :background kuju-sel-inact :extend t)

   ;; ── Magit ────────────────────────────────────────────────────────────────
   (magit-header-line                   :foreground kuju-accent    :background bg-alt)
   (magit-section-heading               :foreground kuju-accent   )
   (magit-section-heading-selection     :foreground kuju-func     )
   (magit-section-highlight             :background kuju-cursorline :extend t)
   (magit-diff-hunk-heading             :foreground kuju-fg-dim2   :background bg-alt :extend t)
   (magit-diff-hunk-heading-highlight   :foreground kuju-fg        :background kuju-sel-act  :extend t)
   (magit-diff-added                    :foreground kuju-ok        :background bg-alt :extend t)
   (magit-diff-added-highlight          :foreground kuju-ok        :background kuju-sel-act  :extend t)
   (magit-diff-removed                  :foreground kuju-err       :background bg-alt :extend t)
   (magit-diff-removed-highlight        :foreground kuju-err       :background kuju-sel-inact :extend t)
   (magit-diff-context                  :foreground kuju-fg-dim2   :extend t)
   (magit-diff-context-highlight        :foreground kuju-fg        :background kuju-cursorline :extend t)
   (magit-diffstat-added                :foreground kuju-ok)
   (magit-diffstat-removed              :foreground kuju-err)
   (magit-hash                          :foreground kuju-gutter)
   (magit-log-date                      :foreground kuju-fg-dim2)
   (magit-log-graph                     :foreground kuju-border)
   (magit-log-author                    :foreground kuju-func)
   (magit-branch-local                  :foreground kuju-accent   )
   (magit-branch-remote                 :foreground kuju-ok       )
   (magit-branch-current                :foreground kuju-accent   )
   (magit-tag                           :foreground kuju-warn)
   (magit-filename                      :foreground kuju-fg)
   (magit-process-ok                    :foreground kuju-ok)
   (magit-process-ng                    :foreground kuju-err)

   ;; ── Company ──────────────────────────────────────────────────────────────
   (company-tooltip                     :foreground kuju-fg        :background bg-alt)
   (company-tooltip-selection           :foreground kuju-fg        :background kuju-sel-act)
   (company-tooltip-common              :foreground kuju-accent   )
   (company-tooltip-common-selection    :foreground kuju-accent   )
   (company-tooltip-annotation          :foreground kuju-gutter)
   (company-tooltip-annotation-selection :foreground kuju-gutter)
   (company-tooltip-scrollbar-thumb     :background bg)
   (company-tooltip-scrollbar-track     :background bg-alt)
   (company-preview-common              :foreground kuju-fg-dim2)
   (company-preview                     :foreground kuju-fg-dim2   :background kuju-cursorline)

   ;; ── Corfu ────────────────────────────────────────────────────────────────
   (corfu-default                       :foreground kuju-fg        :background bg-alt)
   (corfu-current                       :foreground kuju-fg        :background kuju-sel-act)
   (corfu-bar                           :background bg)
   (corfu-border                        :foreground kuju-border)
   (corfu-annotations                   :foreground kuju-gutter)
   (corfu-deprecated                    :foreground kuju-gutter    :strike-through t)

   ;; ── Vertico ──────────────────────────────────────────────────────────────
   (vertico-current                     :foreground kuju-fg        :background kuju-sel-act :extend t)
   (vertico-group-title                 :foreground kuju-accent   )
   (vertico-group-separator             :foreground kuju-border)

   ;; ── Orderless / Consult ──────────────────────────────────────────────────
   (orderless-match-face-0              :foreground kuju-accent   )
   (orderless-match-face-1              :foreground kuju-func     )
   (orderless-match-face-2              :foreground kuju-string   )
   (orderless-match-face-3              :foreground kuju-type     )
   (consult-file                        :foreground kuju-fg)
   (consult-bookmark                    :foreground kuju-accent)
   (consult-preview-cursor              :background kuju-sel-act)

   ;; ── Ivy ──────────────────────────────────────────────────────────────────
   (ivy-current-match                   :foreground kuju-fg        :background kuju-sel-act  :extend t)
   (ivy-minibuffer-match-face-1         :foreground kuju-fg-dim2)
   (ivy-minibuffer-match-face-2         :foreground kuju-accent   )
   (ivy-minibuffer-match-face-3         :foreground kuju-func     )
   (ivy-minibuffer-match-face-4         :foreground kuju-type     )
   (ivy-remote                          :foreground kuju-ok)
   (ivy-modified-buffer                 :foreground kuju-warn)

   ;; ── Which-key ────────────────────────────────────────────────────────────
   (which-key-key-face                  :foreground kuju-accent)
   (which-key-command-description-face  :foreground kuju-fg)
   (which-key-local-map-description-face :foreground kuju-func)
   (which-key-group-description-face    :foreground kuju-type)
   (which-key-separator-face            :foreground kuju-border)
   (which-key-note-face                 :foreground kuju-fg-dim2)
   (which-key-special-key-face          :foreground kuju-value    )

   ;; ── Rainbow delimiters ───────────────────────────────────────────────────
   (rainbow-delimiters-depth-1-face     :foreground kuju-punct)
   (rainbow-delimiters-depth-2-face     :foreground kuju-accent)
   (rainbow-delimiters-depth-3-face     :foreground kuju-func)
   (rainbow-delimiters-depth-4-face     :foreground kuju-type)
   (rainbow-delimiters-depth-5-face     :foreground kuju-string)
   (rainbow-delimiters-depth-6-face     :foreground kuju-keyword)
   (rainbow-delimiters-depth-7-face     :foreground kuju-number)
   (rainbow-delimiters-depth-8-face     :foreground kuju-value)
   (rainbow-delimiters-depth-9-face     :foreground kuju-macro)
   (rainbow-delimiters-mismatched-face  :foreground kuju-err      )
   (rainbow-delimiters-unmatched-face   :foreground kuju-err      )

   ;; ── Org-mode ─────────────────────────────────────────────────────────────
   (org-level-1                         :foreground kuju-heading1 )
   (org-level-2                         :foreground kuju-heading2 )
   (org-level-3                         :foreground kuju-heading2 )
   (org-level-4                         :foreground kuju-heading2)
   (org-level-5                         :foreground kuju-heading2)
   (org-level-6                         :foreground kuju-heading2)
   (org-level-7                         :foreground kuju-heading2)
   (org-level-8                         :foreground kuju-heading2)
   (org-link                            :foreground kuju-keyword   :underline t)
   (org-code                            :foreground kuju-string    :background bg-alt)
   (org-verbatim                        :foreground kuju-string    :background bg-alt)
   (org-block                           :background bg-alt         :extend t)
   (org-block-begin-line                :foreground kuju-fg-dim2   :background bg-alt :extend t)
   (org-block-end-line                  :foreground kuju-fg-dim2   :background bg-alt :extend t)
   (org-document-title                  :foreground kuju-heading1 )
   (org-document-info                   :foreground kuju-fg-dim2)
   (org-document-info-keyword           :foreground kuju-comment)
   (org-meta-line                       :foreground kuju-comment  )
   (org-table                           :foreground kuju-number)
   (org-formula                         :foreground kuju-value)
   (org-quote                           :foreground kuju-comment   :extend t)
   (org-drawer                          :foreground kuju-fg-dim2)
   (org-special-keyword                 :foreground kuju-directive)
   (org-tag                             :foreground kuju-fg-dim2  )
   (org-todo                            :foreground kuju-keyword  )
   (org-done                            :foreground kuju-ok       )
   (org-headline-done                   :foreground kuju-fg-dim2   :strike-through t)
   (org-date                            :foreground kuju-accent    :underline t)
   (org-footnote                        :foreground kuju-accent)
   (org-checkbox                        :foreground kuju-accent   )
   (org-priority                        :foreground kuju-warn)
   (org-warning                         :foreground kuju-warn     )
   (org-ellipsis                        :foreground kuju-fg-dim2)

   ;; ── Markdown ─────────────────────────────────────────────────────────────
   (markdown-header-face                :foreground kuju-heading1 )
   (markdown-header-face-1              :foreground kuju-heading1 )
   (markdown-header-face-2              :foreground kuju-heading2 )
   (markdown-header-face-3              :foreground kuju-heading2 )
   (markdown-header-face-4              :foreground kuju-heading2)
   (markdown-header-face-5              :foreground kuju-heading2)
   (markdown-header-face-6              :foreground kuju-heading2)
   (markdown-code-face                  :background bg-alt         :extend t)
   (markdown-inline-code-face           :foreground kuju-string    :background bg-alt)
   (markdown-pre-face                   :foreground kuju-string    :background bg-alt :extend t)
   (markdown-url-face                   :foreground kuju-keyword   :underline t)
   (markdown-link-face                  :foreground kuju-string)
   (markdown-bold-face                  :foreground kuju-keyword  )
   (markdown-italic-face                :foreground kuju-fg       )
   (markdown-strike-through-face        :foreground kuju-comment   :strike-through t)
   (markdown-blockquote-face            :foreground kuju-comment  )
   (markdown-list-face                  :foreground kuju-keyword)
   (markdown-markup-face                :foreground kuju-punct)

   ;; ── Dired ────────────────────────────────────────────────────────────────
   (dired-directory                     :foreground kuju-accent   )
   (dired-symlink                       :foreground kuju-builtin-v :underline t)
   (dired-special                       :foreground kuju-value)
   (dired-broken-symlink                :foreground kuju-err       :underline t)
   (dired-flagged                       :foreground kuju-err      )
   (dired-marked                        :foreground kuju-warn     )
   (dired-header                        :foreground kuju-accent   )
   (dired-ignored                       :foreground kuju-fg-dim2)

   ;; ── Eshell / vterm ───────────────────────────────────────────────────────
   (eshell-prompt                       :foreground kuju-accent   )
   (eshell-ls-directory                 :foreground kuju-accent   )
   (eshell-ls-symlink                   :foreground kuju-builtin-v :underline t)
   (eshell-ls-executable                :foreground kuju-ok)
   (eshell-ls-missing                   :foreground kuju-err)
   (eshell-ls-archive                   :foreground kuju-value)
   (eshell-ls-backup                    :foreground kuju-fg-dim2)
   (eshell-ls-unreadable                :foreground kuju-err)
   (vterm-color-black                   :foreground bg-alt         :background bg-alt)
   (vterm-color-red                     :foreground kuju-err       :background kuju-err)
   (vterm-color-green                   :foreground kuju-ok        :background kuju-ok)
   (vterm-color-yellow                  :foreground kuju-warn      :background kuju-warn)
   (vterm-color-blue                    :foreground kuju-keyword   :background kuju-keyword)
   (vterm-color-magenta                 :foreground kuju-type      :background kuju-type)
   (vterm-color-cyan                    :foreground kuju-string    :background kuju-string)
   (vterm-color-white                   :foreground kuju-fg        :background kuju-fg)

   ;; ── Tooltip / popup ──────────────────────────────────────────────────────
   (tooltip                             :foreground kuju-fg        :background bg-alt)

   ;; ── Outline ──────────────────────────────────────────────────────────────
   (outline-1                           :foreground kuju-heading1 )
   (outline-2                           :foreground kuju-heading2 )
   (outline-3                           :foreground kuju-heading2)
   (outline-4                           :foreground kuju-heading2)
   (outline-5                           :foreground kuju-heading2)
   (outline-6                           :foreground kuju-heading2)
   (outline-7                           :foreground kuju-heading2)
   (outline-8                           :foreground kuju-heading2)

   ;; ── Misc ─────────────────────────────────────────────────────────────────
   (button                              :foreground kuju-accent    :underline t)
   (link                                :foreground kuju-keyword   :underline t)
   (link-visited                        :foreground kuju-value     :underline t)
   (header-line                         :foreground kuju-fg-dim    :background bg-alt)
   (shadow                              :foreground kuju-fg-dim2))

  ;; ── Extra vars ────────────────────────────────────────────────────────────
  ((ansi-color-names-vector
    (vector "#080B14"  ; 0 black
            "#FF0000"  ; 1 red
            "#33B333"  ; 2 green
            "#E4D97D"  ; 3 yellow
            "#F07178"  ; 4 blue  (mapped to keyword per original)
            "#FFA759"  ; 5 magenta
            "#BAE67E"  ; 6 cyan
            "#CBCEBC"  ; 7 white
            "#E0AD82"  ; 8 bright black
            "#FF0000"  ; 9 bright red
            "#33B333"  ; 10 bright green
            "#E4D97D"  ; 11 bright yellow
            "#599999"  ; 12 bright blue
            "#FFA759"  ; 13 bright magenta
            "#FFCC66"  ; 14 bright cyan
            "#CBCEBC"  ; 15 bright white
            ))))

(provide-theme 'kujukuju)
;;; kujukuju-theme.el ends here
