;;; luna-theme.el --- Luna theme -*- lexical-binding: t; -*-

;; Author: Sublime/Emacs port of luna.nvim
;; URL: https://github.com/WTFox/luna.nvim
;; Keywords: faces theme
;; Package-Requires: ((emacs "27.1"))

;;; Commentary:

;; Luna, ported from the Neovim colorscheme luna.nvim by WTFox.
;;
;; Palette values are taken verbatim from the upstream Lua sources; derived
;; colours use the same blend factors as the plugin.
;;
;; This theme deliberately uses no italics and no underlines anywhere.  It
;; themes both Eglot (`eglot-semantic-*') and lsp-mode (`lsp-face-semhl-*')
;; semantic token faces, and leaves Flymake's in-buffer faces undecorated so
;; diagnostics show up only in the fringe.

;;; Code:

(deftheme luna
  "Luna, ported from the luna.nvim Neovim colorscheme.")

(let ((c '((class color) (min-colors 89)))
      (accent             "#c2916a")
      (accessor           "#a8a8a8")
      (active-guide       "#605958")
      (bg                 "#060606")
      (boolean            "#e19067")
      (bracket            "#a8a8a8")
      (brackets           "#a8a8a8")
      (caret              "#e4e4e8")
      (comment            "#7c7c7c")
      (constant           "#c4a8d6")
      (constant-builtin   "#c4a8d6")
      (decorator          "#7c7c7c")
      (delimiter          "#989898")
      (deprecated         "#605958")
      (diff-add-bg        "#152017")
      (diff-add-fg        "#6fbe80")
      (diff-chg-bg        "#191410")
      (diff-chg-fg        "#c2916a")
      (diff-del-bg        "#40000a")
      (diff-del-fg        "#e08585")
      (diff-header        "#989898")
      (diff-text-bg       "#3e3024")
      (doc-comment        "#7c7c7c")
      (enum               "#c4a8d6")
      (enum-member        "#c4a8d6")
      (error              "#e08585")
      (escape             "#c2916a")
      (fg                 "#e4e4e8")
      (find-bg            "#302028")
      (find-fg            "#f0f0f0")
      (fn-weight          'normal)
      (function           "#75a1c7")
      (function-builtin   "#75a1c7")
      (guide              "#333333")
      (gutter             "#060606")
      (gutter-fg          "#2f2b2b")
      (gutter-hl          "#c7c7c7")
      (highlight          "#c2916a")
      (hint               "#b09080")
      (inactive-selection "#1c1c1c")
      (info               "#8c9cb8")
      (interface          "#c4a8d6")
      (invalid-bg         "#e08585")
      (invalid-fg         "#f0f0f0")
      (invisibles         "#7c7c7c")
      (keyword            "#e19067")
      (keyword-control    "#e19067")
      (keyword-import     "#605958")
      (keyword-operator   "#a8a8a8")
      (keyword-return     "#e19067")
      (klass              "#c4a8d6")
      (kw-weight          'normal)
      (label              "#e19067")
      (line               "#212121")
      (line-diff-add      "#6fbe80")
      (line-diff-del      "#e08585")
      (line-diff-mod      "#c2916a")
      (macro              "#e19067")
      (markup-heading     "#c7c7c7")
      (markup-link        "#6fbe80")
      (markup-list        "#a8a8a8")
      (markup-quote       "#7c7c7c")
      (markup-raw         "#888888")
      (markup-url         "#6fbe80")
      (member             "#e4e4e8")
      (method             "#75a1c7")
      (misspelling        "#e08585")
      (namespace          "#989898")
      (number             "#e19067")
      (ok                 "#6fbe80")
      (operator           "#a8a8a8")
      (param-builtin      "#f3e6de")
      (parameter          "#c7c7c7")
      (popup-bg           "#060606")
      (popup-border       "#404040")
      (popup-fg           "#e4e4e8")
      (property           "#e4e4e8")
      (punctuation        "#a8a8a8")
      (regexp             "#9eb38e")
      (selection          "#404040")
      (selection-border   "#333333")
      (self               "#a8a8a8")
      (stack-guide        "#1f1f1f")
      (storage            "#e19067")
      (string             "#9eb38e")
      (string-alt         "#9eb38e")
      (string-punct       "#9eb38e")
      (tag                "#c4a8d6")
      (tag-attribute      "#e4e4e8")
      (tag-outline        "#c4a8d6")
      (tag-punct          "#a8a8a8")
      (todo               "#c7c7c7")
      (type               "#c4a8d6")
      (type-builtin       "#e19067")
      (variable           "#e4e4e8")
      (warning            "#d9a35a"))
  ;; Bound so the whole palette is available for tweaking, but not
  ;; referenced by any face above.  line-diff-* are unused by design: this
  ;; setup shows no version-control decoration anywhere.
  (ignore active-guide constant-builtin gutter invalid-bg
           keyword-return line-diff-add line-diff-del line-diff-mod
           param-builtin string-punct tag-outline)

  (custom-theme-set-faces
   'luna

     ;; ---- Basic editor faces ----------------------------------------
     `(default ((,c (:background ,bg :foreground ,fg))))
     `(cursor ((,c (:background ,caret :foreground ,bg))))
     `(region ((,c (:background ,selection :extend t))))
     `(mouse-drag-and-drop-region ((,c (:background ,selection-border))))
     `(secondary-selection ((,c (:background ,inactive-selection :extend t))))
     `(highlight ((,c (:background ,line :foreground ,fg))))
     `(hl-line ((,c (:background ,line :extend t))))
     `(fringe ((,c (:background ,bg :foreground ,gutter-fg))))
     `(vertical-border ((,c (:foreground ,guide :background ,bg))))
     `(window-divider ((,c (:foreground ,guide))))
     `(window-divider-first-pixel ((,c (:foreground ,guide))))
     `(window-divider-last-pixel ((,c (:foreground ,guide))))
     `(child-frame-border ((,c (:background ,popup-border))))
     `(internal-border ((,c (:background ,bg))))
     `(minibuffer-prompt ((,c (:foreground ,accent :weight bold))))
     `(shadow ((,c (:foreground ,comment))))
     `(escape-glyph ((,c (:foreground ,escape))))
     `(homoglyph ((,c (:foreground ,warning))))
     `(nobreak-space ((,c (:foreground ,invisibles :underline nil))))
     `(nobreak-hyphen ((,c (:foreground ,invisibles))))
     `(trailing-whitespace ((,c (:background ,diff-del-bg))))
     `(whitespace-tab ((,c (:foreground ,invisibles :background nil))))
     `(whitespace-space ((,c (:foreground ,invisibles :background nil))))
     `(whitespace-newline ((,c (:foreground ,invisibles :background nil))))
     `(whitespace-trailing ((,c (:background ,diff-del-bg :foreground ,fg))))
     `(whitespace-line ((,c (:background ,line :foreground ,fg))))
     `(fill-column-indicator ((,c (:foreground ,guide :weight normal))))
     `(tooltip ((,c (:background ,popup-bg :foreground ,popup-fg))))
     `(error ((,c (:foreground ,error :weight bold :underline nil))))
     `(warning ((,c (:foreground ,warning :weight normal :underline nil))))
     `(success ((,c (:foreground ,ok :weight normal :underline nil))))
     `(link ((,c (:foreground ,markup-url :underline nil :weight normal))))
     `(link-visited ((,c (:foreground ,markup-link :underline nil :weight normal))))
     `(button ((,c (:foreground ,accent :underline nil :weight normal))))
     `(help-key-binding ((,c (:foreground ,accent :background ,line :box nil))))
     `(bold ((,c (:weight bold :slant normal :underline nil))))
     `(italic ((,c (:slant normal :underline nil))))
     `(bold-italic ((,c (:weight bold :slant normal :underline nil))))
     `(underline ((,c (:underline nil))))
     `(fixed-pitch ((,c (:family unspecified))))
     `(fixed-pitch-serif ((,c (:family unspecified :slant normal))))
     `(variable-pitch ((,c (:family unspecified :slant normal))))

     ;; ---- Line numbers ----------------------------------------------
     `(line-number ((,c (:foreground ,gutter-fg :background ,bg :slant normal :weight normal :underline nil))))
     `(line-number-current-line ((,c (:foreground ,gutter-hl :background ,line :weight bold :slant normal :underline nil))))
     `(line-number-major-tick ((,c (:foreground ,gutter-hl :background ,bg :weight normal))))
     `(line-number-minor-tick ((,c (:foreground ,gutter-fg :background ,bg :weight normal))))

     ;; ---- Mode line / header line / tab bar -------------------------
     `(mode-line ((,c (:background ,line :foreground ,fg :box nil))))
     `(mode-line-active ((,c (:background ,line :foreground ,fg :box nil))))
     `(mode-line-inactive ((,c (:background ,bg :foreground ,comment :box nil))))
     `(mode-line-highlight ((,c (:background ,selection :foreground ,fg :box nil))))
     `(mode-line-buffer-id ((,c (:foreground ,accent :weight bold))))
     `(mode-line-emphasis ((,c (:foreground ,accent :weight bold))))
     `(header-line ((,c (:background ,line :foreground ,fg :box nil))))
     `(header-line-highlight ((,c (:background ,selection :foreground ,fg))))
     `(tab-bar ((,c (:background ,line :foreground ,comment))))
     `(tab-bar-tab ((,c (:background ,bg :foreground ,accent :weight bold :box nil))))
     `(tab-bar-tab-inactive ((,c (:background ,line :foreground ,comment :box nil))))
     `(tab-line ((,c (:background ,line :foreground ,comment))))

     ;; ---- Search / matching -----------------------------------------
     `(isearch ((,c (:background ,find-bg :foreground ,find-fg :weight bold :underline nil))))
     `(isearch-fail ((,c (:background ,diff-del-bg :foreground ,error :weight bold))))
     `(isearch-group-1 ((,c (:background ,accent :foreground ,bg))))
     `(isearch-group-2 ((,c (:background ,markup-url :foreground ,bg))))
     `(lazy-highlight ((,c (:background ,selection :foreground ,fg :underline nil))))
     `(match ((,c (:background ,find-bg :foreground ,find-fg))))
     `(query-replace ((,c (:background ,find-bg :foreground ,find-fg))))
     `(show-paren-match ((,c (:background ,selection :foreground ,bracket :weight bold))))
     `(show-paren-match-expression ((,c (:background ,stack-guide))))
     `(show-paren-mismatch ((,c (:background ,invalid-fg :foreground ,bg :weight bold))))
     `(completions-common-part ((,c (:foreground ,accent :weight bold))))
     `(completions-first-difference ((,c (:foreground ,fg :weight bold))))
     `(completions-annotations ((,c (:foreground ,comment :slant normal))))
     `(next-error ((,c (:background ,selection :extend t))))
     `(next-error-message ((,c (:background ,line :extend t))))

     ;; ---- font-lock -------------------------------------------------
     `(font-lock-comment-face ((,c (:foreground ,comment :slant normal :underline nil))))
     `(font-lock-comment-delimiter-face ((,c (:foreground ,comment :slant normal))))
     `(font-lock-doc-face ((,c (:foreground ,doc-comment :slant normal))))
     `(font-lock-doc-markup-face ((,c (:foreground ,markup-raw :slant normal))))
     `(font-lock-string-face ((,c (:foreground ,string))))
     `(font-lock-keyword-face ((,c (:foreground ,keyword :weight ,kw-weight))))
     `(font-lock-builtin-face ((,c (:foreground ,function-builtin))))
     `(font-lock-function-name-face ((,c (:foreground ,function :weight ,fn-weight))))
     `(font-lock-function-call-face ((,c (:foreground ,function))))
     `(font-lock-variable-name-face ((,c (:foreground ,variable))))
     `(font-lock-variable-use-face ((,c (:foreground ,variable))))
     `(font-lock-type-face ((,c (:foreground ,type))))
     `(font-lock-constant-face ((,c (:foreground ,constant))))
     `(font-lock-preprocessor-face ((,c (:foreground ,keyword-import :slant normal))))
     `(font-lock-negation-char-face ((,c (:foreground ,keyword-operator :weight bold))))
     `(font-lock-warning-face ((,c (:foreground ,warning :weight bold :underline nil))))
     `(font-lock-number-face ((,c (:foreground ,number))))
     `(font-lock-operator-face ((,c (:foreground ,operator))))
     `(font-lock-property-name-face ((,c (:foreground ,property))))
     `(font-lock-property-use-face ((,c (:foreground ,member))))
     `(font-lock-punctuation-face ((,c (:foreground ,punctuation))))
     `(font-lock-bracket-face ((,c (:foreground ,brackets))))
     `(font-lock-delimiter-face ((,c (:foreground ,delimiter))))
     `(font-lock-escape-face ((,c (:foreground ,escape))))
     `(font-lock-misc-punctuation-face ((,c (:foreground ,punctuation))))
     `(font-lock-regexp-face ((,c (:foreground ,regexp))))
     `(font-lock-regexp-grouping-backslash ((,c (:foreground ,escape :weight bold))))
     `(font-lock-regexp-grouping-construct ((,c (:foreground ,escape :weight bold))))

     ;; ---- Eglot -----------------------------------------------------
     `(eglot-highlight-symbol-face ((,c (:background ,selection :weight bold :underline nil))))
     `(eglot-mode-line ((,c (:foreground ,accent :weight bold))))
     `(eglot-diagnostic-tag-unnecessary-face ((,c (:foreground ,deprecated :underline nil :slant normal))))
     `(eglot-diagnostic-tag-deprecated-face ((,c (:foreground ,deprecated :underline nil :slant normal))))
     `(eglot-inlay-hint-face ((,c (:foreground ,deprecated :background ,line :height 0.9 :slant normal :underline nil))))
     `(eglot-type-hint-face ((,c (:foreground ,type :background ,line :height 0.9 :slant normal))))
     `(eglot-parameter-hint-face ((,c (:foreground ,parameter :background ,line :height 0.9 :slant normal))))
     `(eglot-code-action-indicator-face ((,c (:foreground ,accent :weight bold :underline nil))))
     `(eglot-semantic-namespace ((,c (:foreground ,namespace))))
     `(eglot-semantic-type ((,c (:foreground ,type))))
     `(eglot-semantic-class ((,c (:foreground ,klass))))
     `(eglot-semantic-enum ((,c (:foreground ,enum))))
     `(eglot-semantic-interface ((,c (:foreground ,interface))))
     `(eglot-semantic-struct ((,c (:foreground ,type))))
     `(eglot-semantic-typeParameter ((,c (:foreground ,type))))
     `(eglot-semantic-parameter ((,c (:foreground ,parameter))))
     `(eglot-semantic-variable ((,c (:foreground ,variable))))
     `(eglot-semantic-property ((,c (:foreground ,property))))
     `(eglot-semantic-enumMember ((,c (:foreground ,enum-member))))
     `(eglot-semantic-event ((,c (:foreground ,function))))
     `(eglot-semantic-function ((,c (:foreground ,function))))
     `(eglot-semantic-method ((,c (:foreground ,method))))
     `(eglot-semantic-macro ((,c (:foreground ,macro))))
     `(eglot-semantic-keyword ((,c (:foreground ,keyword))))
     `(eglot-semantic-modifier ((,c (:foreground ,storage))))
     `(eglot-semantic-comment ((,c (:foreground ,comment))))
     `(eglot-semantic-string ((,c (:foreground ,string))))
     `(eglot-semantic-number ((,c (:foreground ,number))))
     `(eglot-semantic-regexp ((,c (:foreground ,regexp))))
     `(eglot-semantic-operator ((,c (:foreground ,operator))))
     `(eglot-semantic-decorator ((,c (:foreground ,decorator))))
     `(eglot-semantic-declaration ((,c (:weight bold))))
     `(eglot-semantic-definition ((,c (:weight bold))))
     `(eglot-semantic-readonly ((,c (:foreground ,constant))))
     `(eglot-semantic-static ((,c (:foreground ,constant))))
     `(eglot-semantic-deprecated ((,c (:foreground ,deprecated :strike-through t :underline nil))))
     `(eglot-semantic-abstract ((,c (:weight bold))))
     `(eglot-semantic-async ((,c (:foreground ,keyword-control))))
     `(eglot-semantic-modification ((,c (:foreground ,variable))))
     `(eglot-semantic-documentation ((,c (:foreground ,doc-comment :slant normal))))
     `(eglot-semantic-defaultLibrary ((,c (:foreground ,type-builtin))))

     ;; ---- lsp-mode semantic tokens ----------------------------------
     `(lsp-face-semhl-constant ((,c (:foreground ,constant))))
     `(lsp-face-semhl-variable ((,c (:foreground ,variable))))
     `(lsp-face-semhl-function ((,c (:foreground ,function))))
     `(lsp-face-semhl-method ((,c (:foreground ,method))))
     `(lsp-face-semhl-namespace ((,c (:foreground ,namespace))))
     `(lsp-face-semhl-comment ((,c (:foreground ,comment))))
     `(lsp-face-semhl-keyword ((,c (:foreground ,keyword))))
     `(lsp-face-semhl-string ((,c (:foreground ,string))))
     `(lsp-face-semhl-number ((,c (:foreground ,number))))
     `(lsp-face-semhl-regexp ((,c (:foreground ,regexp))))
     `(lsp-face-semhl-operator ((,c (:foreground ,operator))))
     `(lsp-face-semhl-type ((,c (:foreground ,type))))
     `(lsp-face-semhl-struct ((,c (:foreground ,type))))
     `(lsp-face-semhl-class ((,c (:foreground ,klass))))
     `(lsp-face-semhl-interface ((,c (:foreground ,interface))))
     `(lsp-face-semhl-enum ((,c (:foreground ,enum))))
     `(lsp-face-semhl-type-parameter ((,c (:foreground ,type))))
     `(lsp-face-semhl-member ((,c (:foreground ,member))))
     `(lsp-face-semhl-property ((,c (:foreground ,property))))
     `(lsp-face-semhl-event ((,c (:foreground ,function))))
     `(lsp-face-semhl-macro ((,c (:foreground ,macro))))
     `(lsp-face-semhl-parameter ((,c (:foreground ,parameter))))
     `(lsp-face-semhl-label ((,c (:foreground ,label))))
     `(lsp-face-semhl-enum-member ((,c (:foreground ,enum-member))))
     `(lsp-face-semhl-modifier ((,c (:foreground ,storage))))
     `(lsp-face-semhl-decorator ((,c (:foreground ,decorator))))
     `(lsp-face-semhl-default-library ((,c (:foreground ,type-builtin))))
     `(lsp-face-semhl-static ((,c (:foreground ,constant))))
     `(lsp-face-semhl-deprecated ((,c (:foreground ,deprecated :strike-through t :underline nil))))
     `(lsp-face-semhl-definition ((,c (:foreground ,function :weight bold))))
     `(lsp-face-semhl-implementation ((,c (:foreground ,function :weight bold))))
     `(lsp-face-highlight-textual ((,c (:background ,selection))))
     `(lsp-face-highlight-read ((,c (:background ,selection))))
     `(lsp-face-highlight-write ((,c (:background ,diff-chg-bg))))
     `(lsp-inlay-hint-face ((,c (:foreground ,deprecated :background ,line :height 0.9 :slant normal))))
     `(lsp-details-face ((,c (:foreground ,comment :height 0.9 :slant normal))))
     `(lsp-signature-face ((,c (:foreground ,parameter))))
     `(lsp-headerline-breadcrumb-path-face ((,c (:foreground ,comment))))
     `(lsp-headerline-breadcrumb-symbols-face ((,c (:foreground ,fg :weight bold))))

     ;; ---- Flymake -- fringe only, no in-buffer decoration -----------
     `(flymake-error ((,c (:underline nil :background nil :foreground unspecified))))
     `(flymake-warning ((,c (:underline nil :background nil :foreground unspecified))))
     `(flymake-note ((,c (:underline nil :background nil :foreground unspecified))))
     `(flymake-error-echo ((,c (:foreground ,error :underline nil))))
     `(flymake-warning-echo ((,c (:foreground ,warning :underline nil))))
     `(flymake-note-echo ((,c (:foreground ,hint :underline nil))))
     `(flymake-error-echo-at-eol ((,c (:foreground ,error :height 0.9))))
     `(flymake-warning-echo-at-eol ((,c (:foreground ,warning :height 0.9))))
     `(flymake-note-echo-at-eol ((,c (:foreground ,info :height 0.9))))
     `(flymake-end-of-line-diagnostics-face ((,c (:foreground ,comment :height 0.9 :slant normal :box nil))))
     `(flymake-error-fringe ((,c (:foreground ,error :background ,bg))))
     `(flymake-warning-fringe ((,c (:foreground ,warning :background ,bg))))
     `(flymake-note-fringe ((,c (:foreground ,hint :background ,bg))))
     `(flycheck-error ((,c (:underline nil :background nil))))
     `(flycheck-warning ((,c (:underline nil :background nil))))
     `(flycheck-info ((,c (:underline nil :background nil))))
     `(flycheck-fringe-error ((,c (:foreground ,error :background ,bg))))
     `(flycheck-fringe-warning ((,c (:foreground ,warning :background ,bg))))
     `(flycheck-fringe-info ((,c (:foreground ,info :background ,bg))))

     ;; ---- Compilation / grep / xref ---------------------------------
     `(compilation-error ((,c (:foreground ,error :weight bold :underline nil))))
     `(compilation-warning ((,c (:foreground ,warning :weight normal :slant normal :underline nil))))
     `(compilation-info ((,c (:foreground ,ok :weight normal :underline nil))))
     `(compilation-line-number ((,c (:foreground ,number :underline nil))))
     `(compilation-column-number ((,c (:foreground ,comment :underline nil))))
     `(compilation-mode-line-exit ((,c (:foreground ,ok :weight bold))))
     `(compilation-mode-line-fail ((,c (:foreground ,error :weight bold))))
     `(compilation-mode-line-run ((,c (:foreground ,warning :weight bold))))
     `(grep-context-face ((,c (:foreground ,comment))))
     `(grep-error-face ((,c (:foreground ,error :weight bold :underline nil))))
     `(grep-hit-face ((,c (:foreground ,ok))))
     `(grep-match-face ((,c (:background ,find-bg :foreground ,find-fg :weight bold))))
     `(xref-file-header ((,c (:foreground ,accent :weight bold))))
     `(xref-line-number ((,c (:foreground ,gutter-fg))))
     `(xref-match ((,c (:background ,find-bg :foreground ,find-fg))))
     `(eldoc-highlight-function-argument ((,c (:foreground ,accent :weight bold :underline nil))))

     ;; ---- Dired -----------------------------------------------------
     `(dired-header ((,c (:foreground ,accent :weight bold))))
     `(dired-directory ((,c (:foreground ,type :weight bold))))
     `(dired-symlink ((,c (:foreground ,markup-url :underline nil :slant normal))))
     `(dired-broken-symlink ((,c (:foreground ,error :underline nil :weight bold))))
     `(dired-marked ((,c (:foreground ,warning :weight bold))))
     `(dired-flagged ((,c (:foreground ,error :weight bold))))
     `(dired-mark ((,c (:foreground ,accent :weight bold))))
     `(dired-perm-write ((,c (:foreground ,warning))))
     `(dired-set-id ((,c (:foreground ,error))))
     `(dired-special ((,c (:foreground ,constant))))
     `(dired-ignored ((,c (:foreground ,comment :slant normal))))
     `(dired-warning ((,c (:foreground ,warning :weight bold :underline nil))))

     ;; ---- Ido -------------------------------------------------------
     `(ido-first-match ((,c (:foreground ,accent :weight bold))))
     `(ido-only-match ((,c (:foreground ,ok :weight bold))))
     `(ido-subdir ((,c (:foreground ,type))))
     `(ido-virtual ((,c (:foreground ,comment))))
     `(ido-indicator ((,c (:foreground ,bg :background ,warning :weight bold))))
     `(ido-incomplete-regexp ((,c (:foreground ,error :weight bold))))

     ;; ---- Org mode --------------------------------------------------
     `(org-document-title ((,c (:foreground ,markup-heading :weight bold :slant normal :underline nil))))
     `(org-document-info ((,c (:foreground ,markup-link :slant normal))))
     `(org-document-info-keyword ((,c (:foreground ,comment :slant normal))))
     `(org-level-1 ((,c (:foreground ,markup-heading :weight bold :slant normal :underline nil :extend t))))
     `(org-level-2 ((,c (:foreground ,function :weight bold :slant normal :underline nil :extend t))))
     `(org-level-3 ((,c (:foreground ,type :weight bold :slant normal :underline nil :extend t))))
     `(org-level-4 ((,c (:foreground ,string :weight bold :slant normal :underline nil :extend t))))
     `(org-level-5 ((,c (:foreground ,keyword :slant normal :underline nil))))
     `(org-level-6 ((,c (:foreground ,constant :slant normal :underline nil))))
     `(org-level-7 ((,c (:foreground ,member :slant normal :underline nil))))
     `(org-level-8 ((,c (:foreground ,markup-link :slant normal :underline nil))))
     `(org-headline-done ((,c (:foreground ,comment :strike-through nil))))
     `(org-block ((,c (:background ,line :foreground ,fg :extend t))))
     `(org-block-begin-line ((,c (:background ,line :foreground ,comment :slant normal :extend t :underline nil))))
     `(org-block-end-line ((,c (:background ,line :foreground ,comment :slant normal :extend t :underline nil))))
     `(org-code ((,c (:foreground ,markup-raw :background ,line))))
     `(org-verbatim ((,c (:foreground ,markup-raw :background ,line))))
     `(org-quote ((,c (:foreground ,markup-quote :slant normal :extend t))))
     `(org-verse ((,c (:foreground ,markup-quote :slant normal))))
     `(org-list-dt ((,c (:foreground ,markup-list :weight bold))))
     `(org-cite ((,c (:foreground ,markup-link :underline nil))))
     `(org-table ((,c (:foreground ,type))))
     `(org-table-header ((,c (:foreground ,accent :weight bold))))
     `(org-link ((,c (:foreground ,markup-url :underline nil :slant normal))))
     `(org-footnote ((,c (:foreground ,markup-url :underline nil))))
     `(org-date ((,c (:foreground ,markup-link :underline nil :slant normal))))
     `(org-todo ((,c (:foreground ,error :weight bold :underline nil))))
     `(org-done ((,c (:foreground ,ok :weight bold :underline nil))))
     `(org-checkbox ((,c (:foreground ,keyword :weight bold))))
     `(org-checkbox-statistics-todo ((,c (:foreground ,warning :weight bold))))
     `(org-checkbox-statistics-done ((,c (:foreground ,ok :weight bold))))
     `(org-drawer ((,c (:foreground ,comment :slant normal))))
     `(org-special-keyword ((,c (:foreground ,comment :slant normal))))
     `(org-meta-line ((,c (:foreground ,comment :slant normal))))
     `(org-property-value ((,c (:foreground ,constant))))
     `(org-tag ((,c (:foreground ,comment :weight normal :slant normal))))
     `(org-priority ((,c (:foreground ,warning :weight bold))))
     `(org-ellipsis ((,c (:foreground ,comment :underline nil :weight normal))))
     `(org-hide ((,c (:foreground ,bg :background ,bg))))
     `(org-warning ((,c (:foreground ,error :weight bold :underline nil))))
     `(org-agenda-structure ((,c (:foreground ,markup-heading :weight bold))))
     `(org-agenda-date ((,c (:foreground ,markup-link :underline nil))))
     `(org-agenda-date-today ((,c (:foreground ,accent :weight bold :underline nil :slant normal))))
     `(org-agenda-date-weekend ((,c (:foreground ,comment :underline nil :weight normal))))
     `(org-agenda-done ((,c (:foreground ,ok :slant normal))))
     `(org-scheduled ((,c (:foreground ,ok))))
     `(org-scheduled-today ((,c (:foreground ,ok :weight bold))))
     `(org-scheduled-previously ((,c (:foreground ,warning))))
     `(org-upcoming-deadline ((,c (:foreground ,warning))))
     `(org-time-grid ((,c (:foreground ,comment))))
     `(org-formula ((,c (:foreground ,operator))))
     `(org-macro ((,c (:foreground ,macro))))
     `(org-latex-and-related ((,c (:foreground ,constant))))

     ;; ---- Diff / ediff (no VC integration in this config) -----------
     `(diff-added ((,c (:foreground ,diff-add-fg :background ,diff-add-bg :extend t))))
     `(diff-removed ((,c (:foreground ,diff-del-fg :background ,diff-del-bg :extend t))))
     `(diff-changed ((,c (:foreground ,diff-chg-fg :background ,diff-chg-bg :extend t))))
     `(diff-changed-unspecified ((,c (:foreground ,diff-chg-fg :background ,diff-chg-bg :extend t))))
     `(diff-indicator-added ((,c (:foreground ,diff-add-fg :background ,diff-add-bg :weight bold))))
     `(diff-indicator-removed ((,c (:foreground ,diff-del-fg :background ,diff-del-bg :weight bold))))
     `(diff-indicator-changed ((,c (:foreground ,diff-chg-fg :background ,diff-chg-bg :weight bold))))
     `(diff-refine-added ((,c (:foreground ,diff-add-fg :background ,diff-text-bg :weight bold))))
     `(diff-refine-removed ((,c (:foreground ,diff-del-fg :background ,diff-text-bg :weight bold))))
     `(diff-refine-changed ((,c (:foreground ,diff-chg-fg :background ,diff-text-bg :weight bold))))
     `(diff-header ((,c (:foreground ,diff-header :background ,line :extend t))))
     `(diff-file-header ((,c (:foreground ,accent :background ,line :weight bold :extend t))))
     `(diff-hunk-header ((,c (:foreground ,markup-heading :background ,line :extend t))))
     `(diff-function ((,c (:foreground ,function :background ,line))))
     `(diff-context ((,c (:foreground ,comment))))
     `(diff-nonexistent ((,c (:foreground ,error :weight bold))))
     `(ediff-current-diff-A ((,c (:background ,diff-del-bg :extend t))))
     `(ediff-current-diff-B ((,c (:background ,diff-add-bg :extend t))))
     `(ediff-current-diff-C ((,c (:background ,diff-chg-bg :extend t))))
     `(ediff-fine-diff-A ((,c (:background ,diff-text-bg :weight bold))))
     `(ediff-fine-diff-B ((,c (:background ,diff-text-bg :weight bold))))
     `(ediff-fine-diff-C ((,c (:background ,diff-text-bg :weight bold))))
     `(ediff-even-diff-A ((,c (:background ,line :extend t))))
     `(ediff-even-diff-B ((,c (:background ,line :extend t))))
     `(ediff-odd-diff-A ((,c (:background ,line :extend t))))
     `(ediff-odd-diff-B ((,c (:background ,line :extend t))))

     ;; ---- Misc built-ins --------------------------------------------
     `(info-title-1 ((,c (:foreground ,markup-heading :weight bold))))
     `(info-title-2 ((,c (:foreground ,function :weight bold))))
     `(info-title-3 ((,c (:foreground ,type :weight bold))))
     `(info-title-4 ((,c (:foreground ,string :weight bold))))
     `(info-menu-star ((,c (:foreground ,accent))))
     `(Info-quoted ((,c (:foreground ,markup-raw :slant normal))))
     `(help-argument-name ((,c (:foreground ,parameter :slant normal))))
     `(custom-variable-tag ((,c (:foreground ,type :weight bold))))
     `(custom-group-tag ((,c (:foreground ,markup-heading :weight bold))))
     `(custom-state ((,c (:foreground ,ok))))
     `(widget-field ((,c (:background ,line :foreground ,fg :box nil))))
     `(widget-button ((,c (:foreground ,accent :weight bold :underline nil))))
     `(which-func ((,c (:foreground ,function))))
     `(comint-highlight-prompt ((,c (:foreground ,accent :weight bold))))
     `(comint-highlight-input ((,c (:foreground ,fg :weight normal))))
     `(term-color-black ((,c (:foreground ,bg :background ,bg))))
     `(term-color-red ((,c (:foreground ,error :background ,error))))
     `(term-color-green ((,c (:foreground ,ok :background ,ok))))
     `(term-color-yellow ((,c (:foreground ,warning :background ,warning))))
     `(term-color-blue ((,c (:foreground ,function :background ,function))))
     `(term-color-magenta ((,c (:foreground ,type :background ,type))))
     `(term-color-cyan ((,c (:foreground ,info :background ,info))))
     `(term-color-white ((,c (:foreground ,fg :background ,fg))))

     ;; ---- Server-specific semantic tokens (Eglot; add to `eglot-semantic-token-types') 
     `(eglot-semantic-selfKeyword ((,c (:foreground ,self :weight bold))))
     `(eglot-semantic-selfTypeKeyword ((,c (:foreground ,self :weight bold))))
     `(eglot-semantic-builtinType ((,c (:foreground ,type-builtin))))
     `(eglot-semantic-builtinAttribute ((,c (:foreground ,decorator))))
     `(eglot-semantic-attribute ((,c (:foreground ,decorator))))
     `(eglot-semantic-derive ((,c (:foreground ,decorator))))
     `(eglot-semantic-deriveHelper ((,c (:foreground ,decorator))))
     `(eglot-semantic-lifetime ((,c (:foreground ,constant))))
     `(eglot-semantic-typeAlias ((,c (:foreground ,type))))
     `(eglot-semantic-union ((,c (:foreground ,type))))
     `(eglot-semantic-constParameter ((,c (:foreground ,constant))))
     `(eglot-semantic-escapeSequence ((,c (:foreground ,escape))))
     `(eglot-semantic-formatSpecifier ((,c (:foreground ,escape))))
     `(eglot-semantic-character ((,c (:foreground ,string-alt))))
     `(eglot-semantic-boolean ((,c (:foreground ,boolean))))
     `(eglot-semantic-magicFunction ((,c (:foreground ,function-builtin))))
     `(eglot-semantic-unresolvedReference ((,c (:foreground ,invalid-fg :weight bold))))
     `(eglot-semantic-punctuation ((,c (:foreground ,punctuation))))
     `(eglot-semantic-brace ((,c (:foreground ,brackets))))
     `(eglot-semantic-bracket ((,c (:foreground ,brackets))))
     `(eglot-semantic-parenthesis ((,c (:foreground ,brackets))))
     `(eglot-semantic-angle ((,c (:foreground ,brackets))))
     `(eglot-semantic-comma ((,c (:foreground ,delimiter))))
     `(eglot-semantic-colon ((,c (:foreground ,delimiter))))
     `(eglot-semantic-semicolon ((,c (:foreground ,delimiter))))
     `(eglot-semantic-dot ((,c (:foreground ,accessor))))
     `(eglot-semantic-macroBang ((,c (:foreground ,macro))))
     `(eglot-semantic-label ((,c (:foreground ,label))))
     `(eglot-semantic-typeParameterName ((,c (:foreground ,type))))

     ;; ---- Markup / XML / spelling / misc packages -------------------
     `(nxml-element-local-name ((,c (:foreground ,tag))))
     `(nxml-tag-delimiter ((,c (:foreground ,tag-punct))))
     `(nxml-tag-slash ((,c (:foreground ,tag-punct))))
     `(nxml-attribute-local-name ((,c (:foreground ,tag-attribute))))
     `(nxml-attribute-value ((,c (:foreground ,string))))
     `(nxml-namespace-attribute-prefix ((,c (:foreground ,namespace))))
     `(nxml-comment-content ((,c (:foreground ,comment :slant normal))))
     `(nxml-processing-instruction-target ((,c (:foreground ,keyword-import))))
     `(sgml-namespace ((,c (:foreground ,namespace))))
     `(flyspell-incorrect ((,c (:foreground ,misspelling :underline nil :weight bold))))
     `(flyspell-duplicate ((,c (:foreground ,warning :underline nil :weight bold))))
     `(hl-todo ((,c (:foreground ,todo :weight bold :underline nil))))
     `(pulse-highlight-start-face ((,c (:background ,highlight))))
     `(bookmark-face ((,c (:foreground ,markup-list :background ,line))))
     `(markdown-header-face ((,c (:foreground ,markup-heading :weight bold))))
     `(markdown-inline-code-face ((,c (:foreground ,markup-raw :background ,line))))
     `(markdown-code-face ((,c (:foreground ,fg :background ,line :extend t))))
     `(markdown-url-face ((,c (:foreground ,markup-url :underline nil))))
     `(markdown-link-face ((,c (:foreground ,markup-link :underline nil))))
     `(markdown-italic-face ((,c (:slant normal :foreground ,markup-list))))
     `(markdown-bold-face ((,c (:weight bold :foreground ,markup-list))))
     `(markdown-pre-face ((,c (:foreground ,markup-raw :background ,line))))
     `(markdown-blockquote-face ((,c (:foreground ,markup-quote :slant normal))))
     `(markdown-list-face ((,c (:foreground ,markup-list)))))

  (custom-theme-set-variables
   'luna
   `(ansi-color-names-vector
     [,bg ,error ,ok ,warning ,function ,type ,info ,fg])))

(provide-theme 'luna)

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

;;; luna-theme.el ends here
