theme = "kujukuju"

[editor]
line-number = "relative"
gutters = ["diagnostics", "spacer" , "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[keys.normal.space]
"m" = ":run-shell-command just run"
"M" = ":run-shell-command just debug"
