[editor.colors]
default_font_color = 0xddddddff
whitespace = 0x46474129
carriage_return = 0xb38f8fff
search_result = 0xdbad49aa
selection_color = 0x393b31
token_match = 0xddddddaa
active_line_number = 0xb4aa60ff
inactive_line_number = 0x444444ff
line_number_sep = 0x939799ff
line_ruler = 0x3a3a37ff
cursor = 0x40ff40ff
prim_cursor = 0xdbad49ff
tray = 0xddddddff
need_save = 0xb38f8fff
background = 0xff
warning = 0xebcb8bff
error = 0xb38f8fff
auto_line_ending = 0xb3a3d3
vim_cursor_color = 0xb3a3d3
async_highlight = 0x8fa3b347
selected_editor = 0x6ac6f2
line_guides = 0x75715e26
active_line_guide = 0xb4aa60ff
highlight_line_copy = 0xa3be8c
highlight_line_edit = 0xebcb8b
cursor_line_outline = 0x3a3a3750
cursor_line_fill = 0x32332b50

[editor.state]
show_line_numbers = true
auto_syntax_highlighting = true
auto_line_endings = true
save_on_cmd_launch = false
render_whitespace = false
tabs_as_spaces = true
spellcheck_by_default = false
disable_line_highlight = false
html_copy_background = true
vim_mode = false
suppress_async_search = false
suppress_threaded_search = false
suppress_suggestions = false
modulate_color_glyphs = false
embold_vim_cursor = true
embold_cursor = false
line_guides = true
relative_numbering = true
clear_find = false
return_accept_suggestion = true
show_line_rulers = false
enable_active_line_fill = false
enable_prim_cursor_fill = false
noisy_parse = false
noisy_search = false
noisy_events = false
noisy_flattened_events = false
noisy_find_all = false
font_size_px = 26
tray_font_size = 26
tabstop = 4
line_number_style = 'LineNumberStyle_Classic'
line_rulers = []

[[editor.highlights]]
color = 0xdbad49ff
tags = ['keyword.directive',
'keyword.directive.define',
'keyword.directive.include',
'macro.function',
'macro.define',
'macro.definition']

[[editor.highlights]]
color = 0xdbad49ff
tags = ['keyword.alloc',
'keyword.return',
'keyword.repeat',
'keyword.conditional',
'keyword.exception',
'keyword.coroutine',
'keyword.coroutine.return']

[[editor.highlights]]
color = 0x708b8dff
tags = ['keyword.conditional.ternary']

[[editor.highlights]]
color = 0xdbad49ff
tags = ['keyword',
'keyword.storage',
'type.qualifier',
'tag']

[[editor.highlights]]
color = 0x708b8dff
tags = ['keyword.operator',
'type.builtin']

[[editor.highlights]]
color = 0x819affff
tags = ['boolean']

[[editor.highlights]]
color = 0x71ade7ff
tags = ['function.builtin']

[[editor.highlights]]
color = 0xdbad49ff
tags = ['variable.builtin']

[[editor.highlights]]
color = 0x71ade7ff
tags = ['function']

[[editor.highlights]]
color = 0x7aade7ff
tags = ['function.call']

[[editor.highlights]]
color = 0x71ade7ff
tags = ['function.method',
'function.method.call']

[[editor.highlights]]
color = 0x708b8dff
tags = ['type']

[[editor.highlights]]
color = 0xddddddff
tags = ['property']

[[editor.highlights]]
color = 0x678e87ff
tags = ['attribute']

[[editor.highlights]]
color = 0x939799ff
tags = ['constant',
'constant.builtin']

[[editor.highlights]]
color = 0x819affff
tags = ['number']

[[editor.highlights]]
color = 0x98c379ff
tags = ['string',
'character']

[[editor.highlights]]
color = 0x678e87ff
tags = ['string.escape']

[[editor.highlights]]
color = 0x727169ff
tags = ['comment']

[[editor.highlights]]
color = 0x708b8dff
tags = ['operator']

[[editor.highlights]]
color = 0x708b8dff
tags = ['scope.name']

[[editor.highlights]]
color = 0x939799ff
tags = ['embedded']

[diff.colors]
del = 0xb38f8fff
ins = 0xa3be8c
eq = 0xddddddff
trimmed_text = 0xebcb8bff
graph_link = 0xdbad49ff
selected_node_color = 0xdbad49aa
last_save_node_color = 0xa3be8c
external_change_node_color = 0xebcb8bff

[diff.state]
diff_font_size = 22

[file_explorer.colors]
default_font_color = 0xddddddff
relative_dir_font_color = 0x75715eff
actively_rooted = 0xdbad49
background = 0xff
selection_color = 0x393b31aa
match_color = 0xdbad49aa
directory_color = 0x708b8dff
unknown_color = 0xb38f8fff
B_color = 0xddddddff
KB_color = 0x8fa3b3ff
MB_color = 0xb3a3d3ff
GB_color = 0xebcb8bff
TB_color = 0xdbad49ff
PB_color = 0xb38f8fff
EB_color = 0xddddddff

[file_explorer.state]
font_size = 24
noisy_dir_root = false
rooted_filters = ""

[feed.colors]
info = 0xddddddff
warning = 0xebcb8bff
error = 0xb38f8fff

[feed.state]
feed_font_size = 22

[widget.colors]
window_border = 0x93979926
window_background = 0x050505cb
window_title_background = 0x93979926
window_title_font_color = 0xddddddff
window_close_button_hover = 0xb38f8fff
window_close_button_pressed = 0x8f6b6bff
scrollbar_inactive = 0x93979926
scrollbar_active = 0xdbad49ff
scrollbar_track_outline = 0x93979926
custom_hotkey_fill = 0xa3be8c
drag_drop_zone = 0xdbad49ff
outline_selection = 0xdbad49
warning = 0xebcb8bff
error = 0xb38f8fff
good = 0xa3be8c
active_button = 0xdbad49
loading_bar_progress = 0xa3be8c
loading_bar_complete = 0x8fa3b3
active_tab_highlight = 0xdbad49
active_selection = 0xdbad49

[widget.state]
window_title_font_size = 20
scrollbar_width = 10
scrollbar_min_size = 20

[system.core]
preferred_file_explorer = 'C:\Program Files\Voidstar\FilePilot\FPilot.exe'
core_window_rect = [190, 190, 1366, 768]
async_update_frequency_ms = 1000
editor_theme = 'ColorTheme_Fred'
error_match_strat = 'ErrorMatcher_None'
fullscreen = false
maximized = true
disable_sessions = true
disable_plugins = false
noisy_session_info = false

[system.fonts]
fallback_fonts_folder = 'C:\Windows\Fonts'
current_font = './fonts/IBMPlexMono-Regular.ttf'

[system.effects]
audio_keystroke = []
audio_return = []
postprocessing_enabled = true
screen_warp = true
multipass_crt = true
mute_audio = false
suppress_audio_startup = true
crt_mode = false
animate_cursor = true
light_mode = false
smooth_scroll = true
highlight_line_copy = true
highlight_line_edit = true
subpixel_font_aa = false

[hotkey.state]
hotkeys = 'C:\Users\glens\AppData\Roaming\cadacama\fred\hotkeys.toml'

[plugins.core]
plugins_source_file = 'G:\Programs\fred\plugins\plugin.c'
gen_base_template_only = false
exclude_examples = false